// Regenerates fixtures/tenseal-gate.json.gz from the independent TenSEAL SEAL build.
// Usage: node crosscheck/make-fixture.mjs <python-with-tenseal>
// This fixture is SELF-GENERATED by a second SEAL implementation (TenSEAL's bundled SEAL). It is
// not an official standard test vector; it exists so the TypeScript path is checked against ciphertexts
// it did not produce. The secret key inside is a throw-away test key.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const py = process.argv[2];
if (!py) throw new Error('usage: make-fixture.mjs <python>');
const dir = mkdtempSync(join(tmpdir(), 'pca-fhe-fx-'));
const req = {
  inputs: [100, 900, 100, 100, 100, 100],
  weights: [250, 200, 200, 200, 100, 50],
  kappaWeights: [250, 200, 200, 200, 100, 50],
  budget: 600000,
  withGalois: false,
};
writeFileSync(join(dir, 'in.json'), JSON.stringify(req));
execFileSync(py, [join(here, 'seal_xcheck.py'), 'gen', join(dir, 'in.json'), join(dir, 'out.json')], { stdio: 'inherit' });
const out = JSON.parse(readFileSync(join(dir, 'out.json'), 'utf8'));
const fixture = {
  provenance: {
    kind: 'self-generated cross-implementation fixture (NOT an official standard test vector)',
    generator: 'packages/pca-fhe/crosscheck/seal_xcheck.py gen',
    library: `TenSEAL ${out.tenseal} (tenseal.sealapi, bundled Microsoft SEAL)`,
    params: 'BFV, poly modulus 8192, BFVDefault coeff modulus (128-bit), batching plain modulus 1073692673',
    generatedOn: new Date().toISOString().slice(0, 10),
    note: 'secretKey is a throw-away test key. Stream headers were re-stamped (version byte + uncompressed envelope) by seal_xcheck.py so node-seal can load them; coefficients are untouched.',
  },
  request: req,
  secretKey: out.secretKey,
  encInputs: out.encInputs,
  encRiskRaw: out.encRiskRaw,
  encSlack: out.encSlack,
  expected: { riskRaw: out.riskRaw, slack: out.slack },
};
writeFileSync(join(here, '..', 'fixtures', 'tenseal-gate.json.gz'), gzipSync(JSON.stringify(fixture), { level: 9 }));
