/**
 * Cross-check @atlasauth/pca-sdjwt against the independent `@sd-jwt/*` JavaScript libraries.
 * Setup:   npm i --prefix "$SDJWT_LIB" @sd-jwt/core@0.22.0 @sd-jwt/crypto-nodejs@0.19.0
 * Run:     SDJWT_LIB=/path/to/dir node crosscheck/sdjwt-js.mts
 * Output:  fixtures/sd-jwt-js.json (credentials issued by @sd-jwt/* for the TS tests to verify with pca-sdjwt)
 * Also:    issues + presents with pca-sdjwt and VERIFIES it with @sd-jwt/core (exits non-zero on failure).
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateKeyPair, exportJWK, importJWK } from 'jose';
import { issuePcaSdJwt, present } from '../src/index.ts';

const lib = process.env.SDJWT_LIB;
if (!lib) throw new Error('set SDJWT_LIB');
const req = createRequire(resolve(lib, 'x.js'));
const { SDJwtInstance } = req('@sd-jwt/core');
const { ES256, digest, generateSalt } = req('@sd-jwt/crypto-nodejs');
const ver = (n: string): string => JSON.parse(readFileSync(resolve(lib, 'node_modules', n, 'package.json'), 'utf8')).version;
const coreVersion = ver('@sd-jwt/core');
const cryptoVersion = ver('@sd-jwt/crypto-nodejs');

const kp = await generateKeyPair('ES256', { extractable: true });
const issuerPriv = await exportJWK(kp.privateKey);
const issuerPub = await exportJWK(kp.publicKey);
const holder = await generateKeyPair('ES256', { extractable: true });
const holderPriv = await exportJWK(holder.privateKey);
const holderPub = await exportJWK(holder.publicKey);

const base = { hasher: digest, hashAlg: 'sha-256', saltGenerator: generateSalt, signAlg: 'ES256', kbSignAlg: 'ES256' };
const inst = new SDJwtInstance({
  ...base,
  signer: await ES256.getSigner(issuerPriv),
  verifier: await ES256.getVerifier(issuerPub),
  kbSigner: await ES256.getSigner(holderPriv),
  kbVerifier: async (data: string, sig: string) => (await ES256.getVerifier(holderPub))(data, sig),
});

const claims = { iss: 'https://theirs.example', iat: 1700000000, exp: 4000000000, cnf: { jwk: holderPub }, given_name: 'Ada', family_name: 'Lovelace',
  address: { street: '1 Main', city: 'London', zip: 'N1' }, nationalities: ['GB', 'FR', 'US'] };
const frame = { _sd: ['given_name', 'family_name'], address: { _sd: ['street', 'city'] }, nationalities: { _sd: [0, 2] } };
const issued = await inst.issue(claims, frame);
const pres = await inst.present(issued, { given_name: true, address: { city: true }, nationalities: { 0: true } }, { kb: { payload: { iat: 1700000100, aud: 'https://rp.example', nonce: 'nonce-77' } } });

const out = {
  generator: `@sd-jwt/core ${coreVersion} + @sd-jwt/crypto-nodejs ${cryptoVersion} (independent implementation), generated by crosscheck/sdjwt-js.mts`,
  issuer_public_jwk: issuerPub,
  issued, presentation: pres,
  presentation_kb: { aud: 'https://rp.example', nonce: 'nonce-77', iat: 1700000100 },
  expect: { given_name: 'Ada', address: { city: 'London' }, nationalities: ['GB'] },
};
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'sd-jwt-js.json'), JSON.stringify(out, null, 1));
console.log('wrote fixtures/sd-jwt-js.json');

// ---- Direction 2: pca-sdjwt output verified by @sd-jwt/core ----
const pcActn = {
  ver: 'pca/1', aud: 'https://rp.example', iat: 1700000000000, exp: 4000000000000, action: { kind: 'refund', amount: 5 }, grant_ref: 'g-1', nonce: 'abc',
  cap_chain: [{ issuer: 'https://issuer.pca.example', holder: Buffer.from(holderPub.x ?? '', 'base64url').toString('base64url') }], sig: 'sigsig',
};
const hk = holderPub;
const sdjwt = await issuePcaSdJwt(pcActn as never, { issuerKey: kp.privateKey, signingAlg: 'ES256', keyBinding: { holderPublicKey: hk } });
const mine = await present(sdjwt, ['action', 'nonce'], { keyBinding: { holderKey: holder.privateKey, audience: 'https://rp.example', nonce: 'n-9', iat: 1700000100, alg: 'ES256' } });
const verifyInst = new SDJwtInstance({ ...base, verifier: await ES256.getVerifier(issuerPub), kbVerifier: async (d: string, s: string) => (await ES256.getVerifier(holderPub))(d, s) });
const v = await verifyInst.verify(mine, { requiredClaimKeys: ['action'], keyBindingNonce: 'n-9' });
if (v.payload.action === undefined || (v.payload as Record<string, unknown>).sig !== undefined) throw new Error('unexpected disclosure set from @sd-jwt/core');
console.log('@sd-jwt/core verified a pca-sdjwt presentation with KB-JWT; disclosed action =', JSON.stringify(v.payload.action));
// negative: wrong nonce must be rejected by the independent library
let rejected = false;
try { await verifyInst.verify(mine, { requiredClaimKeys: ['action'], keyBindingNonce: 'wrong' }); } catch { rejected = true; }
if (!rejected) throw new Error('@sd-jwt/core accepted a wrong nonce');
console.log('@sd-jwt/core rejected wrong nonce as expected');
void importJWK;
