// Regenerates crosscheck-ml-dsa-65.json (NOT official vectors): ML-DSA-65 through PCA's wrappers vs
// two independent implementations (dilithium-py, liboqs). Requires built ../../pca/dist.
// Usage: node testdata/crosscheck-ml-dsa.mjs <venv-python>
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const pca = require(join(here, '..', '..', 'pca', 'dist', 'index.js'));
const py = process.argv[2];
if (!py) throw new Error('usage: crosscheck-ml-dsa.mjs <venv-python>');
const hx = (b) => Buffer.from(b).toString('hex');
const sh = (label, n) => createHash('shake256', { outputLength: n }).update(label).digest();

const msgLens = [0, 1, 32, 33, 100, 1000];
const noble = msgLens.map((len, i) => {
  const seed = sh(`mldsa-seed-${i}`, 32);
  const kp = pca.mlDsa65Keygen(seed);
  const msg = sh(`mldsa-msg-${i}`, len);
  const sig = pca.mlDsa65Sign(kp.secretKey, msg);
  if (!pca.mlDsa65Verify(kp.publicKey, msg, sig)) throw new Error('self-verify failed');
  return { seed: hx(seed), pk: hx(kp.publicKey), msg: hx(msg), sig: hx(sig) };
});
// liboqs-python prints a banner line to stdout; the JSON result is the last line.
const raw = execFileSync(py, ['-I', join(here, 'crosscheck_ml_dsa.py')], { input: JSON.stringify({ noble }), maxBuffer: 1 << 28 }).toString().trim().split('\n');
const res = JSON.parse(raw[raw.length - 1]);
for (const r of res.noble_checked) if (!r.dilithium_py_verifies || !r.liboqs_verifies || !r.tampered_rejected) throw new Error('independent library disagreed: ' + JSON.stringify(r));
const out = {
  provenance: {
    kind: 'cross-implementation vectors generated by this repo (NOT official NIST vectors; see acvp-ml-dsa-65.json for those)',
    independent_implementations: res.versions,
    pca_ml_dsa: 'ML-DSA via @atlasauth/pca (@noble/post-quantum), pure external interface, empty context',
    generated: new Date().toISOString().slice(0, 10),
  },
  noble_signed: noble.map((c, i) => ({ ...c, ...res.noble_checked[i] })),
  dilithium_py: res.dilithium_py,
  liboqs: res.liboqs,
};
writeFileSync(join(here, 'crosscheck-ml-dsa-65.json'), JSON.stringify(out, null, 1) + '\n');
console.log('ok', res.versions);
