/**
 * BUILT-IN, release-signed pins for the Azure MAA token-signing keys: the offline root of the first accepted key set.
 *
 * WHAT SHIPS: a signed allowlist manifest (`attest-maa-pins.data.ts`, generated by `scripts/sign-maa-pins.ts`)
 * carrying (a) `maa-signing-spki` pins for the self-signed per-instance MAA keys, (b) the SPKI pin of the
 * Microsoft chain root and of the `Microsoft Azure Attestation PCA 2019` intermediate that Microsoft-chained keys
 * must pass through, and (c) a signed `attest-corroboration` record of how many independent network vantage points
 * saw identical key material and by what method. The manifest is verified at load against the issuer public key
 * EMBEDDED in this package, with the usual expiry / version-floor checks (`verifyAllowlistManifest`).
 *
 * WHAT IS GUARANTEED
 *   - With the default `createMaaKeyTrust` policy there is NO trust-on-first-use: the first accepted key set must
 *     overlap these signed pins (then the normal rotation rules apply), and Microsoft-chained keys are accepted
 *     only through the pinned root AND intermediate, with the leaf CN `Microsoft Azure Attestation 2020`.
 *   - The manifest cannot be edited, re-signed by another key, rolled back below the shipped version floor, or used
 *     after its expiry (fail closed: pins expire; ship a new release or pass explicit `initialPins`).
 *   - The pin set was corroborated by `>= minVantages` independent vantages at signing time (default requirement 3),
 *     and that count is inside the signed bytes, so a release cannot silently claim more than was recorded.
 *
 * WHAT IS NOT GUARANTEED
 *   - The offline root is the RELEASE SIGNING KEY plus the recorded multi-vantage corroboration. It is not a
 *     Microsoft-issued root for the self-signed instance keys: Microsoft does not publish one. A compromise of the
 *     release key, or of every vantage at signing time, defeats it. Vantage independence is operational, not proven.
 *   - The Microsoft chain root pin IS an anchor in Microsoft's own PKI (Microsoft Root Certificate Authority 2011),
 *     re-checked against Microsoft's published repository at signing time (see the sign script), but this module
 *     narrows it to the MAA intermediate; it does not check CRLs or Microsoft's revocation.
 *   - Pins age: a MAA key the release does not know is accepted only through the rotation rules (<= maxNewKeysPerFetch
 *     unseen keys per fetch, overlap with a known key), never as a fresh root.
 */
import { verifyAllowlistManifest, projectAllowlist, type AllowlistIssuerKey } from './attest-allowlist';
import { BUILTIN_PINS_ISSUER_ID, BUILTIN_PINS_ISSUER_KEY, BUILTIN_PINS_MANIFEST, BUILTIN_PINS_MIN_VERSION } from './attest-maa-pins.data';

/** The leaf CN Microsoft's MAA signing certificates carry. */
export const BUILTIN_CHAIN_LEAF_CN = ['Microsoft Azure Attestation 2020'] as const;

/** Where trust is rooted: the embedded release issuer key. */
export const BUILTIN_MAA_PINS_ISSUER_KEYS: Readonly<Record<string, AllowlistIssuerKey>> = Object.freeze({
  [BUILTIN_PINS_ISSUER_ID]: BUILTIN_PINS_ISSUER_KEY,
});

/** A substitute signed pin source (tests, or a fork that signs its own pins). */
export interface BuiltinMaaPinsSource {
  manifest: unknown;
  issuerKeys: Readonly<Record<string, AllowlistIssuerKey>>;
  /** Rollback floor (default: 1 for a custom source). */
  minVersion?: number;
}

export interface BuiltinMaaPinsOk {
  ok: true;
  version: number;
  digest: string;
  expiresAt: number;
  /** Self-signed instance key pins by issuer URL. */
  maaSigningSpkis: Record<string, string[]>;
  /** Tombstoned instance key pins by issuer URL. */
  revokedSigningSpkis: Record<string, string[]>;
  maaChainRootSpkis: string[];
  maaChainIntermediateSpkis: string[];
  /** Number of independent vantages recorded in the signed corroboration entry. */
  vantages: number;
  /** The signed `method` text of the corroboration entry. */
  method: string;
}
export type BuiltinMaaPinsResult = BuiltinMaaPinsOk | { ok: false; reason: string };

const MAX_LIFETIME_MS = 400 * 24 * 3_600_000;
const MIN_VANTAGES = 3;

interface Verified {
  ok: true;
  value: BuiltinMaaPinsOk;
  notBefore: number;
  expiresAt: number;
}
const memo = new WeakMap<object, Verified | { ok: false; reason: string }>();

function evaluate(src: BuiltinMaaPinsSource, nowMs: number): Verified | { ok: false; reason: string } {
  // Signature + structure are checked at a time inside the window; the window itself is re-checked on every call.
  const v0 = verifyAllowlistManifest(src.manifest, {
    issuerKeys: src.issuerKeys,
    nowMs: (src.manifest as { body?: { notBefore?: number } } | null)?.body?.notBefore ?? nowMs,
    minVersion: src.minVersion ?? 1,
    maxLifetimeMs: MAX_LIFETIME_MS,
  });
  if (!v0.ok) return { ok: false, reason: `${v0.code}: ${v0.reason}` };
  const p = projectAllowlist(v0, { nowMs: v0.body.notBefore });
  const corr = p.corroboration;
  if (corr.length !== 1) return { ok: false, reason: 'manifest must carry exactly one attest-corroboration entry' };
  const m = /^vantages=([0-9]+);method=(.*)$/.exec(corr[0]!.label);
  const vantages = m ? Number(m[1]) : 0;
  if (!m || vantages < MIN_VANTAGES) return { ok: false, reason: `corroboration records ${vantages} vantages < required ${MIN_VANTAGES}` };
  if (Object.keys(p.maaSigningSpkis).length === 0) return { ok: false, reason: 'manifest pins no MAA signing key' };
  if (p.maaChainRootSpkis.length === 0 || p.maaChainIntermediateSpkis.length === 0) return { ok: false, reason: 'manifest lacks the Microsoft chain root / intermediate pins' };
  const revoked: Record<string, string[]> = {};
  for (const r of p.revoked) if (r.kind === 'maa-signing-spki') (revoked[r.label] ??= []).push(r.value);
  return {
    ok: true,
    notBefore: v0.body.notBefore,
    expiresAt: v0.body.expiresAt,
    value: {
      ok: true,
      version: v0.version,
      digest: v0.digest,
      expiresAt: v0.body.expiresAt,
      maaSigningSpkis: p.maaSigningSpkis,
      revokedSigningSpkis: revoked,
      maaChainRootSpkis: p.maaChainRootSpkis,
      maaChainIntermediateSpkis: p.maaChainIntermediateSpkis,
      vantages,
      method: m[2]!,
    },
  };
}

/**
 * Load and verify the built-in pin set at `nowMs`. Never throws. Signature verification is memoised per source
 * object; the validity window is re-checked on every call.
 */
export function loadBuiltinMaaPins(opts: { nowMs: number; source?: BuiltinMaaPinsSource }): BuiltinMaaPinsResult {
  try {
    if (!Number.isSafeInteger(opts.nowMs)) return { ok: false, reason: 'nowMs must be an integer' };
    const src: BuiltinMaaPinsSource = opts.source ?? { manifest: BUILTIN_PINS_MANIFEST, issuerKeys: BUILTIN_MAA_PINS_ISSUER_KEYS, minVersion: BUILTIN_PINS_MIN_VERSION };
    const key: object = opts.source ?? BUILTIN_MAA_PINS_ISSUER_KEYS;
    let r = memo.get(key);
    if (r === undefined) {
      r = evaluate(src, opts.nowMs);
      memo.set(key, r);
    }
    if (!r.ok) return r;
    if (opts.nowMs < r.notBefore) return { ok: false, reason: 'built-in pins are not yet valid (clock behind the release)' };
    if (opts.nowMs > r.expiresAt) return { ok: false, reason: 'built-in pins expired; update the package or pass explicit initialPins' };
    return r.value;
  } catch (e) {
    return { ok: false, reason: e instanceof Error ? e.message : 'built-in pins error' };
  }
}
