/**
 * Official-KAT reproduction through the wasm binding.
 *
 * `src/kat/less-252-45.digest.json` is derived (scripts/make-kat-digest.mjs) from the KAT response
 * file shipped in the upstream LESS repository at the pinned commit
 * (`Utilities/KAT_Generation/KAT/PQCsignKAT_97484.rsp`, 100 entries, the file whose public-key length
 * equals this build's 97484 bytes). The 20 MB .rsp is not committed; the digest stores each entry's
 * seed, message, secret key, smlen and SHA-256 of the public key and signed message, plus the SHA-256
 * of the original .rsp so the derivation is auditable.
 *
 * WHAT THIS PROVES: the wasm reproduces, byte-for-byte, what upstream's own native KAT generator
 * produced. WHAT IT DOES NOT: that the KATs came from an independent implementation (they were
 * generated by the same reference code).
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { keygen, open, seedWith, sign, sizes } from './index.js';

interface KatEntry {
  count: number;
  seed: string;
  msg: string;
  pkSha256: string;
  sk: string;
  smlen: number;
  smSha256: string;
}
interface KatDigest {
  upstreamCommit: string;
  rspSha256: string;
  entries: KatEntry[];
}

const WASM = join(__dirname, '..', 'wasm', 'less_cat1.wasm');
const d = existsSync(WASM) ? describe : describe.skip;
const sha = (b: Uint8Array): string => createHash('sha256').update(b).digest('hex');
const hex = (b: Uint8Array): string => Buffer.from(b).toString('hex');
const digest = JSON.parse(readFileSync(join(__dirname, 'kat', 'less-252-45.digest.json'), 'utf8')) as KatDigest;

describe('official KAT digest metadata', () => {
  it('pins the upstream commit and carries all 100 entries', () => {
    expect(digest.upstreamCommit).toBe('6383430b9123e69d2ef6a6224f930972e3225610');
    expect(digest.rspSha256).toBe('2a9a37787a689a90e49bf74adfdec13483896e586620501030f358ec9752d59f');
    expect(digest.entries).toHaveLength(100);
    expect(digest.entries.map((e) => e.count)).toEqual(Array.from({ length: 100 }, (_, i) => i));
  });
});

d('official LESS KAT (CATEGORY=252 TARGET=45), reproduced by the wasm', () => {
  it('matches all 100 entries byte-for-byte (pk, sk, signed message) and every one opens', () => {
    expect(sizes().publicKey).toBe(97484);
    let matched = 0;
    for (const e of digest.entries) {
      seedWith(Buffer.from(e.seed, 'hex')); // 48-byte NIST KAT seed -> reference SHAKE CSPRNG
      const { publicKey, secretKey } = keygen();
      expect(sha(publicKey), `pk #${e.count}`).toBe(e.pkSha256);
      expect(hex(secretKey), `sk #${e.count}`).toBe(e.sk);
      const msg = Buffer.from(e.msg, 'hex');
      const sm = sign(secretKey, msg);
      expect(sm.length, `smlen #${e.count}`).toBe(e.smlen);
      expect(sha(sm), `sm #${e.count}`).toBe(e.smSha256);
      const r = open(publicKey, sm);
      expect(r.ok, `open #${e.count}`).toBe(true);
      expect(Buffer.from(r.message).equals(msg)).toBe(true);
      matched++;
    }
    expect(matched).toBe(100);
  }, 600_000);
});
