// Regenerates src/embedded.ts (base64 of wasm/less_cat1.wasm) so bundlers/edge runtimes can instantiate
// without a file or a fetch. Run after replacing the wasm; a test asserts the embed matches the file.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const wasm = readFileSync(join(root, 'wasm', 'less_cat1.wasm'));
const b64 = wasm.toString('base64');
const sha = createHash('sha256').update(wasm).digest('hex');
writeFileSync(join(root, 'src', 'embedded.ts'), `// GENERATED by scripts/embed-wasm.mjs -- do not edit.
import { initLess, initLessSync } from './core.js';

/** SHA-256 of the embedded wasm (equals wasm/less_cat1.wasm). */
export const WASM_SHA256 = '${sha}';
/** The wasm, base64-encoded. */
export const WASM_BASE64 =
  '${b64}';

/** Decode the embedded wasm bytes (uses \`atob\`, present in Node >=16, browsers, Deno, Bun, workers). */
export function embeddedWasmBytes(): Uint8Array {
  const bin = atob(WASM_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** Async portable init from the embedded bytes (works on browser main threads). */
export function initLessEmbedded(): Promise<void> {
  return initLess(embeddedWasmBytes());
}

/** Sync init from the embedded bytes (Node/Deno/Bun/workers; not browser main thread). */
export function initLessEmbeddedSync(): void {
  initLessSync(embeddedWasmBytes());
}

export * from './core.js';
`);
console.log('embedded', wasm.length, 'bytes sha256', sha);
