/**
 * Cross-implementation tests for the FN-DSA wasm backend.
 *
 * FIPS 206 has no published NIST/ACVP vectors, so these are NOT official vectors. The fixtures in
 * `test-vectors/fndsa-crosscheck.json` were generated by this repo's `crosscheck/generate.mjs` using an
 * independent implementation of the same draft: the C library `pornin/c-fn-dsa` (a separate code base
 * and language from the Rust `fn-dsa` crate compiled into the wasm). Both directions are covered:
 * C-signed signatures must verify in the wasm, and wasm-signed signatures were verified by the C code
 * at generation time (recorded) and are reproduced bit-for-bit here from their seeds.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { type FnDsaVariant, FnDsaError, keygen, sign, sizes, verify } from './index';

interface CSigned { variant: FnDsaVariant; vk: string; msg: string; sig: string }
interface WasmSigned extends CSigned { keygen_seed: string; sign_seed: string; sk: string; c_impl_verifies: boolean }
interface Fixture {
  c_signed: CSigned[];
  wasm_signed: WasmSigned[];
  c_keygen_vs_wasm_keygen_identical: boolean;
  provenance: { kind: string; c_fn_dsa: { repo: string; commit: string }; generated: string };
}

const fx = JSON.parse(readFileSync(join(__dirname, '..', 'test-vectors', 'fndsa-crosscheck.json'), 'utf8')) as Fixture;
const b = (h: string): Uint8Array => new Uint8Array(Buffer.from(h, 'hex'));
const flip = (x: Uint8Array, i: number, mask = 0x01): Uint8Array => {
  const y = Uint8Array.from(x);
  y[i] = (y[i] ?? 0) ^ mask;
  return y;
};

describe('fixture provenance', () => {
  it('is labelled as non-official cross-implementation data pinned to a c-fn-dsa commit', () => {
    expect(fx.provenance.kind).toMatch(/NOT NIST/);
    expect(fx.provenance.c_fn_dsa.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(fx.c_signed.length).toBeGreaterThanOrEqual(6);
    expect(fx.wasm_signed.length).toBeGreaterThanOrEqual(6);
  });
});

describe('C implementation (c-fn-dsa) -> wasm verify', () => {
  for (const [i, v] of fx.c_signed.entries()) {
    describe(`${v.variant} #${i} (message ${b(v.msg).length} B)`, () => {
      const vk = b(v.vk), msg = b(v.msg), sig = b(v.sig);
      it('a signature produced by the C implementation verifies', () => {
        expect(sig.length).toBe(sizes(v.variant).signature);
        expect(verify(v.variant, vk, msg, sig)).toBe(true);
      });
      it('rejects a modified message', () => {
        expect(verify(v.variant, vk, new Uint8Array([...msg, 0x00]), sig)).toBe(false);
      });
      it('rejects a different verifying key (same-size foreign key)', () => {
        const other = fx.c_signed.find((o, j) => j !== i && o.variant === v.variant && o.vk !== v.vk);
        expect(other).toBeDefined();
        expect(verify(v.variant, b(other!.vk), msg, sig)).toBe(false);
      });
      it('rejects a wrong header byte (non-canonical encoding)', () => {
        expect(verify(v.variant, vk, msg, flip(sig, 0, 0x80))).toBe(false);
      });
      it('rejects non-zero padding after the compressed vector', () => {
        const last = sig.length - 1;
        expect(sig[last]).toBe(0); // padding region is zero in a canonical signature
        expect(verify(v.variant, vk, msg, flip(sig, last))).toBe(false);
      });
      it('rejects a verifying key with a wrong header byte', () => {
        expect(verify(v.variant, flip(vk, 0, 0x01), msg, sig)).toBe(false);
      });
      it('rejects EVERY single-bit flip of the signature', () => {
        for (let bit = 0; bit < sig.length * 8; bit++) {
          if (verify(v.variant, vk, msg, flip(sig, bit >> 3, 1 << (bit & 7)))) {
            throw new Error(`single-bit flip ${bit} still verified`);
          }
        }
      });
    });
  }
});

describe('wasm -> C implementation (recorded) and wasm determinism', () => {
  for (const [i, v] of fx.wasm_signed.entries()) {
    it(`${v.variant} #${i}: the C implementation accepted this signature and the wasm reproduces it from its seeds`, () => {
      expect(v.c_impl_verifies).toBe(true);
      const kp = keygen(v.variant, b(v.keygen_seed));
      expect(Buffer.from(kp.verifyingKey).toString('hex')).toBe(v.vk);
      expect(Buffer.from(kp.signingKey).toString('hex')).toBe(v.sk);
      const s = sign(v.variant, kp.signingKey, b(v.msg), b(v.sign_seed));
      expect(Buffer.from(s).toString('hex')).toBe(v.sig);
      expect(verify(v.variant, kp.verifyingKey, b(v.msg), s)).toBe(true);
    });
  }
});

describe('error reasons are specific', () => {
  const vk = b(fx.c_signed[0]!.vk), sig = b(fx.c_signed[0]!.sig);
  it('wrong-size verifying key names the field and sizes', () => {
    expect(() => verify('fn-dsa-512', vk.slice(1), new Uint8Array(1), sig)).toThrow(/verifyingKey: expected 897 bytes, got 896/);
  });
  it('wrong-size signature names the field and sizes', () => {
    expect(() => verify('fn-dsa-512', vk, new Uint8Array(1), sig.slice(1))).toThrow(/signature: expected 666 bytes, got 665/);
  });
  it('wrong-size seed / signing key / oversized message each fail with FnDsaError', () => {
    expect(() => keygen('fn-dsa-512', new Uint8Array(31))).toThrow(/seed: expected 32 bytes, got 31/);
    expect(() => sign('fn-dsa-512', new Uint8Array(10), new Uint8Array(1), new Uint8Array(32))).toThrow(/signingKey: expected 1345 bytes, got 10/);
    expect(() => verify('fn-dsa-512', vk, new Uint8Array(1 << 20), sig)).toThrow(FnDsaError);
  });
  it('a 666-byte signature is not accepted for fn-dsa-1024 (size mismatch)', () => {
    expect(() => verify('fn-dsa-1024', new Uint8Array(1793), new Uint8Array(1), sig)).toThrow(/signature: expected 1280 bytes, got 666/);
  });
  it('a well-sized but undecodable verifying key (all 0xFF) returns false, not true', () => {
    expect(verify('fn-dsa-512', new Uint8Array(897).fill(0xff), new Uint8Array(1), sig)).toBe(false);
  });
});

// Optional live differential test: set FNDSA_CX_BIN to a build of crosscheck/cx.c + c-fn-dsa.
const cx = process.env['FNDSA_CX_BIN'];
describe.skipIf(cx === undefined || cx === '')('live differential against the C implementation', () => {
  const run = (...a: string[]): string => execFileSync(cx as string, a).toString().trim();
  for (const variant of ['fn-dsa-512', 'fn-dsa-1024'] as const) {
    it(`${variant}: fresh keys signed by each side verify on the other`, () => {
      const logn = variant === 'fn-dsa-512' ? '9' : '10';
      for (let t = 0; t < 3; t++) {
        const seed = Buffer.alloc(32, t + 1);
        const [csk, cvk] = run('keygen', logn, seed.toString('hex')).split(' ') as [string, string];
        const msg = Buffer.from(`live ${t}`);
        const csig = run('sign', csk, msg.toString('hex'), Buffer.alloc(40, t + 9).toString('hex'));
        expect(verify(variant, b(cvk), msg, b(csig))).toBe(true);
        const kp = keygen(variant, seed);
        const wsig = sign(variant, kp.signingKey, msg, Buffer.alloc(32, t + 5));
        expect(run('verify', Buffer.from(kp.verifyingKey).toString('hex'), msg.toString('hex'), Buffer.from(wsig).toString('hex'))).toBe('1');
      }
    });
  }
});
