// Regenerates test-vectors/fndsa-crosscheck.json: cross-implementation vectors for the wasm backend.
// Requires: built dist/ (pnpm build) and the C binary built from crosscheck/cx.c + pornin/c-fn-dsa.
// Usage: node crosscheck/generate.mjs <cx-binary>
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const wasm = require(join(here, '..', 'dist', 'index.js'));
const [cx] = process.argv.slice(2);
if (!cx) throw new Error('usage: generate.mjs <cx-binary>');

const hx = (b) => Buffer.from(b).toString('hex');
const gen = (label, n) => createHash('shake256', { outputLength: n }).update(label).digest();
const C = (...args) => execFileSync(cx, args.map(String)).toString().trim();
const LOGN = { 'fn-dsa-512': 9, 'fn-dsa-1024': 10 };
const msgs = ['', 'a', 'The quick brown fox jumps over the lazy dog', 'x'.repeat(1000)].map((s) => Buffer.from(s));

const out = { c_signed: [], wasm_signed: [], c_keygen_vs_wasm_keygen_identical: null };
for (const variant of ['fn-dsa-512', 'fn-dsa-1024']) {
  // C keygen + C sign -> wasm must verify
  for (let i = 0; i < 3; i++) {
    const [sk, vk] = C('keygen', LOGN[variant], hx(gen(`${variant}:ckg:${i}`, 32))).split(' ');
    const msg = msgs[i % msgs.length];
    const sig = C('sign', sk, hx(msg), hx(gen(`${variant}:csg:${i}`, 40)));
    out.c_signed.push({ variant, seed_note: `shake256("${variant}:ckg:${i}")`, vk, msg: hx(msg), sig });
  }
  // wasm keygen + wasm sign -> C must verify
  for (let i = 0; i < 3; i++) {
    const seed = gen(`${variant}:wkg:${i}`, 32);
    const { verifyingKey, signingKey } = wasm.keygen(variant, seed);
    const msg = msgs[(i + 1) % msgs.length];
    const sigSeed = gen(`${variant}:wsg:${i}`, 32);
    const sig = wasm.sign(variant, signingKey, msg, sigSeed);
    const cOk = C('verify', hx(verifyingKey), hx(msg), hx(sig)) === '1';
    if (!cOk) throw new Error(`C implementation rejected a wasm signature (${variant} #${i})`);
    out.wasm_signed.push({ variant, keygen_seed: hx(seed), sign_seed: hx(sigSeed), vk: hx(verifyingKey), sk: hx(signingKey), msg: hx(msg), sig: hx(sig), c_impl_verifies: cOk });
  }
}
// Is seeded keygen identical across implementations? (Informational: the draft does not specify it.)
{
  const seed = gen('same-seed', 32);
  const w = wasm.keygen('fn-dsa-512', seed);
  const [sk, vk] = C('keygen', 9, hx(seed)).split(' ');
  out.c_keygen_vs_wasm_keygen_identical = hx(w.verifyingKey) === vk && hx(w.signingKey) === sk;
}
out.provenance = {
  kind: 'cross-implementation vectors generated by this repo (NOT NIST/official vectors; FIPS 206 has no published ACVP vectors)',
  c_fn_dsa: { repo: 'https://github.com/pornin/c-fn-dsa', commit: process.env.CFNDSA_COMMIT ?? 'unset' },
  generated: new Date().toISOString().slice(0, 10),
};
writeFileSync(join(here, '..', 'test-vectors', 'fndsa-crosscheck.json'), JSON.stringify(out, null, 1) + '\n');
console.log('c_signed', out.c_signed.length, 'wasm_signed', out.wasm_signed.length, 'identical keygen:', out.c_keygen_vs_wasm_keygen_identical);
