"""Cross-check @atlasauth/pca-dpop against PyJWT (independent implementation).
Run: uv run --with pyjwt==2.10.1 --with cryptography python crosscheck/pyjwt_crosscheck.py
Direction 1: verify a proof made by pca-dpop (fixtures/ours.json) with PyJWT.
Direction 2: write a proof made by PyJWT (fixtures/pyjwt.json) that the TS tests verify with pca-dpop."""
import base64, json, pathlib, jwt
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization

here = pathlib.Path(__file__).parent.parent / 'fixtures'
b = lambda s: base64.urlsafe_b64decode(s + '=' * (-len(s) % 4))
u = lambda v: base64.urlsafe_b64encode(v).rstrip(b'=').decode()

ours = json.loads((here / 'ours.json').read_text())
hdr = jwt.get_unverified_header(ours['proof'])
assert hdr['typ'] == 'dpop+jwt' and hdr['alg'] == 'EdDSA'
pub = Ed25519PublicKey.from_public_bytes(b(hdr['jwk']['x']))
claims = jwt.decode(ours['proof'], pub, algorithms=['EdDSA'], options={'verify_iat': False, 'verify_exp': False})
assert claims['htm'] == 'POST' and claims['htu'] == 'https://server.example.com/token' and claims['nonce'] == 'n-1'
print('PyJWT', jwt.__version__, 'verified pca-dpop proof OK')

seed = bytes.fromhex('4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb')  # RFC 8032 test vector 3 seed
sk = Ed25519PrivateKey.from_private_bytes(seed)
x = u(sk.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw))
ed = jwt.encode({'htm': 'GET', 'htu': 'https://api.example.com/r', 'iat': 1700000000, 'jti': 'pyjwt-ed-1'}, sk, algorithm='EdDSA',
                headers={'typ': 'dpop+jwt', 'jwk': {'kty': 'OKP', 'crv': 'Ed25519', 'x': x}})
ek = ec.derive_private_key(int('c9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721', 16), ec.SECP256R1())  # RFC 6979 A.2.5 key
n = ek.public_key().public_numbers()
ej = {'kty': 'EC', 'crv': 'P-256', 'x': u(n.x.to_bytes(32, 'big')), 'y': u(n.y.to_bytes(32, 'big'))}
es = jwt.encode({'htm': 'POST', 'htu': 'https://api.example.com/r', 'iat': 1700000000, 'jti': 'pyjwt-es-1', 'nonce': 'srv-n'}, ek, algorithm='ES256',
                headers={'typ': 'dpop+jwt', 'jwk': ej})
(here / 'pyjwt.json').write_text(json.dumps({
    'generator': f'PyJWT {jwt.__version__} (pyca/cryptography); keys are RFC 8032 / RFC 6979 published test keys; generated by crosscheck/pyjwt_crosscheck.py',
    'ed25519': ed, 'es256': es}, indent=2))
print('wrote fixtures/pyjwt.json')
