/**
 * External-vector and cross-implementation tests for pca-vc.
 *  - multibase base58btc vectors: multiformats/multibase tests (basic, leading_zero, two_leading_zeros)
 *  - did:key spec DIDs (w3c-ccg/did-key-spec)
 *  - 43 did:key values generated by the Python `multiformats` + `base58` libraries
 *  - RFC 9421 requests signed by / verified with the Python `http-message-signatures` library
 * Provenance for each is in the matching file under fixtures/ or in the comment beside it.
 */
import { createPublicKey, generateKeyPairSync } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SignJWT } from 'jose';
import { describe, expect, it } from 'vitest';
import { issuePassport } from '@atlasauth/pca';
import {
  base58btcDecode,
  base58btcEncode,
  didKeyFromEd25519,
  ed25519FromDidKey,
  passportToVC,
  verifyPassportVC,
  verifyRequestSignature,
} from './index';

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}
function fixture(name: string): Record<string, unknown> {
  const raw: unknown = JSON.parse(readFileSync(resolve(__dirname, '..', 'fixtures', name), 'utf8'));
  if (!isRecord(raw)) throw new Error(`bad fixture ${name}`);
  return raw;
}
const hex = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'hex'));
const ascii = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'latin1'));

describe('base58btc: multiformats/multibase official vectors', () => {
  // multiformats/multibase @ d7406cdea189b82a0b3937f5737b440f5fa92f92 (2025-05-11), tests/*.csv, base58btc rows (z-prefixed).
  const cases: Array<[string, Uint8Array, string]> = [
    ['basic.csv', ascii('yes mani !'), '7paNL19xttacUY'],
    ['leading_zero.csv', Uint8Array.from([0, ...ascii('yes mani !')]), '17paNL19xttacUY'],
    ['two_leading_zeros.csv', Uint8Array.from([0, 0, ...ascii('yes mani !')]), '117paNL19xttacUY'],
  ];
  for (const [file, bytes, enc] of cases) {
    it(`${file}: encode and decode`, () => {
      expect(base58btcEncode(bytes)).toBe(enc);
      expect(Array.from(base58btcDecode(enc))).toEqual(Array.from(bytes));
    });
  }
  it('rejects characters outside the alphabet (0, O, I, l)', () => {
    for (const bad of ['0abc', 'Oabc', 'Iabc', 'labc', 'ab c', 'ab+c']) {
      expect(() => base58btcDecode(bad)).toThrow(/invalid base58btc/);
    }
  });
});

describe('did:key', () => {
  it('decodes both Ed25519 DIDs printed in the did:key specification to 32-byte keys', () => {
    for (const did of ['did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK', 'did:key:z6Mkf5rGMoatrSj1f4CyvuHBeXJELe9RPdzo2PKGNCKVtZxP']) {
      const raw = ed25519FromDidKey(did);
      expect(raw.length).toBe(32);
      expect(didKeyFromEd25519(raw)).toBe(did);
    }
  });

  it('rejects a spec secp256k1/P-256 did:key (wrong multicodec) with a type error', () => {
    for (const did of ['did:key:zQ3shokFTS3brHcDQrn82RUDfCZESWL1ZdCEJwekUDPQiYBme', 'did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2']) {
      expect(() => ed25519FromDidKey(did)).toThrow(/not an Ed25519/);
    }
  });

  it('rejects malformed identifiers', () => {
    expect(() => ed25519FromDidKey('did:web:example.com')).toThrow(/not a did:key/);
    expect(() => ed25519FromDidKey('did:key:f6Mkha')).toThrow(/not a did:key/);
    expect(() => ed25519FromDidKey('did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2do')).toThrow(); // truncated
    expect(() => ed25519FromDidKey('did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK0')).toThrow(); // extra char outside alphabet
  });

  it('agrees with the independent Python multiformats/base58 libraries on 43 keys, both directions', () => {
    const fx = fixture('didkey-python.json');
    const vectors = fx.vectors;
    if (!Array.isArray(vectors)) throw new Error('bad fixture');
    expect(vectors.length).toBe(43);
    for (const v of vectors) {
      if (!isRecord(v)) throw new Error('bad vector');
      const raw = hex(String(v.public_key_hex));
      expect(didKeyFromEd25519(raw)).toBe(v.did);
      expect(Array.from(ed25519FromDidKey(String(v.did)))).toEqual(Array.from(raw));
    }
  });
});

describe('passport VC hardening (RFC 9901 shape + fail-closed verifier)', () => {
  const passport = issuePassport({ model_id: 'm', operator: 'op', hardware_rooted: true, issued_at: 1, weights_digest: 'wd', system_prompt_digest: 'sd' });
  const keys = generateKeyPairSync('ed25519');
  const did = didKeyFromEd25519(new Uint8Array(keys.publicKey.export({ format: 'der', type: 'spki' }).subarray(-32)));
  const issue = (): Promise<string> => passportToVC(passport, { issuerKey: keys.privateKey, issuerDid: did, subjectDid: did, ttlSec: 3600 });
  const parts = (vc: string): string[] => vc.split('~');
  const claimsOf = (vc: string): Record<string, unknown> => {
    const c: unknown = JSON.parse(Buffer.from((parts(vc)[0] ?? '').split('.')[1] ?? '', 'base64url').toString('utf8'));
    if (!isRecord(c)) throw new Error('bad jwt');
    return c;
  };

  it('puts _sd_alg at the top level of the payload, never inside credentialSubject (RFC 9901 section 4.1.1)', async () => {
    const vc = await issue();
    const claims = claimsOf(vc);
    expect(claims._sd_alg).toBe('sha-256');
    const cs = (claims.vc as { credentialSubject: Record<string, unknown> }).credentialSubject;
    expect(cs._sd_alg).toBeUndefined();
    expect(Array.isArray(cs._sd)).toBe(true);
  });

  it('rejects HS256 forged with the raw public key bytes as the HMAC secret (algorithm confusion)', async () => {
    const rawPub = new Uint8Array(keys.publicKey.export({ format: 'der', type: 'spki' }).subarray(-32));
    const forged = await new SignJWT({ vc: claimsOf(await issue()).vc })
      .setProtectedHeader({ alg: 'HS256', typ: 'vc+sd-jwt' })
      .setIssuer(did)
      .sign(rawPub);
    await expect(verifyPassportVC(`${forged}~`, rawPub)).rejects.toThrow(/alg/i);
  });

  it('rejects a wrong typ header', async () => {
    const vc = await issue();
    const claims = claimsOf(vc);
    const jwt = await new SignJWT(claims).setProtectedHeader({ alg: 'EdDSA', typ: 'JWT' }).sign(keys.privateKey);
    await expect(verifyPassportVC(`${jwt}~${parts(vc).slice(1).join('~')}`, keys.publicKey)).rejects.toThrow(/typ/);
  });

  it('rejects a VC whose @context does not begin with the VC 2.0 context, and one missing the credential type', async () => {
    const claims = claimsOf(await issue());
    const vc = claims.vc as Record<string, unknown>;
    const sign = (v: Record<string, unknown>): Promise<string> =>
      new SignJWT({ ...claims, vc: v }).setProtectedHeader({ alg: 'EdDSA', typ: 'vc+sd-jwt' }).sign(keys.privateKey);
    await expect(verifyPassportVC(`${await sign({ ...vc, '@context': ['https://www.w3.org/2018/credentials/v1'] })}~`, keys.publicKey)).rejects.toThrow(/@context/);
    await expect(verifyPassportVC(`${await sign({ ...vc, type: ['VerifiableCredential'] })}~`, keys.publicKey)).rejects.toThrow(/type must include/);
  });

  it('rejects a nested _sd_alg and an unsupported top-level _sd_alg', async () => {
    const claims = claimsOf(await issue());
    const vc = claims.vc as { credentialSubject: Record<string, unknown> };
    const sign = (c: Record<string, unknown>): Promise<string> => new SignJWT(c).setProtectedHeader({ alg: 'EdDSA', typ: 'vc+sd-jwt' }).sign(keys.privateKey);
    const nested = await sign({ ...claims, vc: { ...vc, credentialSubject: { ...vc.credentialSubject, _sd_alg: 'sha-256' } } });
    await expect(verifyPassportVC(`${nested}~`, keys.publicKey)).rejects.toThrow(/top-level/);
    const sha512 = await sign({ ...claims, _sd_alg: 'sha-512' });
    await expect(verifyPassportVC(`${sha512}~`, keys.publicKey)).rejects.toThrow(/unsupported _sd_alg/);
  });

  it('rejects a duplicated disclosure and a tampered disclosure', async () => {
    const vc = await issue();
    const p = parts(vc);
    await expect(verifyPassportVC([p[0], p[1], p[1], ''].join('~'), keys.publicKey)).rejects.toThrow(/duplicate/);
    const tampered = Buffer.from(JSON.stringify(['salt', 'weights_digest', 'evil'])).toString('base64url');
    await expect(verifyPassportVC([p[0], tampered, ''].join('~'), keys.publicKey)).rejects.toThrow(/does not match any _sd digest/);
  });

  it('rejects an expired credential', async () => {
    const vc = await passportToVC(passport, { issuerKey: keys.privateKey, issuerDid: did, subjectDid: did, ttlSec: -10 });
    await expect(verifyPassportVC(vc, keys.publicKey)).rejects.toThrow(/exp/);
  });

  it('rejects a credential signed by a different issuer key', async () => {
    const other = generateKeyPairSync('ed25519');
    await expect(verifyPassportVC(await issue(), other.publicKey)).rejects.toThrow(/signature/i);
  });

  it('lets the holder withhold a disclosure and still verifies', async () => {
    const vc = await issue();
    const p = parts(vc);
    const withheld = [p[0], p[1], ''].join('~');
    const out = await verifyPassportVC(withheld, keys.publicKey);
    expect(out.passport.weights_digest).toBe('wd');
    expect(out.passport.system_prompt_digest).toBeUndefined();
  });
});

describe('RFC 9421 cross-implementation: Python http-message-signatures 2.0.1', () => {
  const py = fixture('hms-python.json');
  const ours = fixture('ours-9421.json');
  const pubRaw = hex(String(py.public_key_hex));
  const spki = Buffer.concat([Buffer.from('302a300506032b6570032100', 'hex'), pubRaw]);
  const key = createPublicKey({ key: spki, format: 'der', type: 'spki' });
  const cases = (f: Record<string, unknown>): Array<Record<string, unknown>> => {
    if (!Array.isArray(f.cases)) throw new Error('bad fixture');
    return f.cases.filter(isRecord);
  };
  const args = (c: Record<string, unknown>) => ({
    method: String(c.method),
    url: String(c.url),
    headers: c.headers as Record<string, string>,
    signatureInput: String(c.signatureInput),
    signature: String(c.signature),
  });

  it('verifies requests signed by the Python library', () => {
    expect(cases(py).length).toBe(2);
    for (const c of cases(py)) expect(verifyRequestSignature(args(c), key)).toBe(true);
  });

  it('rejects tampered method, URL, covered header and signature on those requests', () => {
    const c = cases(py)[0];
    if (c === undefined) throw new Error('missing case');
    const a = args(c);
    expect(verifyRequestSignature({ ...a, method: 'DELETE' }, key)).toBe(false);
    expect(verifyRequestSignature({ ...a, url: 'https://api.acme.com/v1/orders?x=2' }, key)).toBe(false);
    expect(verifyRequestSignature({ ...a, headers: { 'content-type': 'text/plain' } }, key)).toBe(false);
    const sig = Buffer.from(a.signature.slice('sig1=:'.length, -1), 'base64');
    sig[0] = (sig[0] ?? 0) ^ 1;
    expect(verifyRequestSignature({ ...a, signature: `sig1=:${sig.toString('base64')}:` }, key)).toBe(false);
  });

  it('still verifies the requests pca-vc signed (these were verified by Python in crosscheck/)', () => {
    for (const c of cases(ours)) {
      const a = args(c);
      const sa = typeof c.signatureAgent === 'string' ? { signatureAgent: c.signatureAgent } : {};
      expect(verifyRequestSignature({ ...a, ...sa }, key)).toBe(true);
    }
  });

  it('enforces required components, algorithm, and freshness on a Python-signed request', () => {
    const c = cases(py)[0];
    if (c === undefined) throw new Error('missing case');
    const a = args(c);
    expect(verifyRequestSignature({ ...a, requiredComponents: ['@method', '@target-uri', 'host'] }, key)).toBe(true);
    expect(verifyRequestSignature({ ...a, requiredComponents: ['@authority'] }, key)).toBe(false);
    const created = Number(/created=(\d+)/.exec(a.signatureInput)?.[1]);
    expect(verifyRequestSignature({ ...a, maxAgeSec: 60, nowSec: created + 30 }, key)).toBe(true);
    expect(verifyRequestSignature({ ...a, maxAgeSec: 60, nowSec: created + 61 }, key)).toBe(false);
    expect(verifyRequestSignature({ ...a, maxAgeSec: 60, nowSec: created - 600 }, key)).toBe(false);
  });
});
