/**
 * ML-DSA-65 (FIPS 204) validation for the hybrid path.
 *
 *  1. OFFICIAL NIST ACVP vectors (testdata/acvp-ml-dsa-65.json, pinned to a usnistgov/ACVP-Server commit,
 *     with the sha256 of each upstream file recorded) run against the exact ML-DSA PCA uses:
 *       - through PCA's own wrappers (`mlDsa65Keygen` / `mlDsa65Sign` / `mlDsaVerify`), which expose the
 *         pure external interface with an EMPTY context;
 *       - through the same pinned `@noble/post-quantum` instance for the vectors that need a context or
 *         the internal / external-mu interfaces (PCA's wrappers do not expose those).
 *  2. Cross-checks against two independent implementations (dilithium-py, liboqs) in both directions
 *     (testdata/crosscheck-ml-dsa-65.json; generated by crosscheck-ml-dsa.mjs, NOT official vectors).
 */

import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ML_DSA_65_PUBLIC_KEY_BYTES, ML_DSA_65_SIGNATURE_BYTES, mlDsa65Keygen, mlDsa65Sign, mlDsa65Verify } from '@atlasauth/pca';

const dir = join(__dirname, '..', 'testdata');
const h = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'hex'));
const hex = (b: Uint8Array): string => Buffer.from(b).toString('hex');

// The same noble instance @atlasauth/pca resolves (not a dependency of this package).
interface NobleSigner {
  keygen(seed: Uint8Array): { publicKey: Uint8Array; secretKey: Uint8Array };
  sign(sk: Uint8Array, msg: Uint8Array, ctx?: Uint8Array, rnd?: Uint8Array): Uint8Array;
  verify(pk: Uint8Array, msg: Uint8Array, sig: Uint8Array, ctx?: Uint8Array): boolean;
  internal: {
    sign(sk: Uint8Array, msg: Uint8Array, rnd?: Uint8Array, externalMu?: boolean): Uint8Array;
    verify(pk: Uint8Array, msg: Uint8Array, sig: Uint8Array, externalMu?: boolean): boolean;
  };
}
const pcaRequire = createRequire(require.resolve('@atlasauth/pca'));
const noble = (pcaRequire('@noble/post-quantum/ml-dsa.js') as { ml_dsa65: NobleSigner }).ml_dsa65;

interface Tc { tcId: number; seed?: string; pk: string; sk?: string; message?: string; mu?: string; context?: string; rnd?: string; signature?: string; testPassed?: boolean; reason?: string }
interface Group { tgId: number; signatureInterface: 'external' | 'internal'; externalMu?: boolean; deterministic?: boolean; tests: Tc[] }
interface Acvp {
  provenance: { kind: string; commit: string; files: { url: string; sha256: string }[] };
  keyGen: Tc[];
  sigGen: Group[];
  sigVer: Group[];
}
const acvp = JSON.parse(readFileSync(join(dir, 'acvp-ml-dsa-65.json'), 'utf8')) as Acvp;
const need = <T>(v: T | undefined, what: string): T => {
  if (v === undefined) throw new Error(`fixture missing ${what}`);
  return v;
};

describe('ACVP provenance', () => {
  it('records the pinned upstream commit and per-file sha256', () => {
    expect(acvp.provenance.kind).toMatch(/OFFICIAL NIST ACVP/);
    expect(acvp.provenance.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(acvp.provenance.files).toHaveLength(3);
    for (const f of acvp.provenance.files) expect(f.sha256).toMatch(/^[0-9a-f]{64}$/);
  });
  it('covers the expected number of official cases', () => {
    expect(acvp.keyGen).toHaveLength(25);
    expect(acvp.sigGen.reduce((n, g) => n + g.tests.length, 0)).toBe(90);
    expect(acvp.sigVer.reduce((n, g) => n + g.tests.length, 0)).toBe(45);
  });
});

describe('ACVP ML-DSA-65 keyGen via PCA mlDsa65Keygen', () => {
  it('reproduces every official (pk, sk) from its seed', () => {
    for (const t of acvp.keyGen) {
      const kp = mlDsa65Keygen(h(need(t.seed, 'seed')));
      expect(hex(kp.publicKey), `tcId ${t.tcId} pk`).toBe(t.pk);
      expect(hex(kp.secretKey), `tcId ${t.tcId} sk`).toBe(t.sk);
    }
  });
});

describe('ACVP ML-DSA-65 sigGen', () => {
  const external = acvp.sigGen.filter((g) => g.signatureInterface === 'external');
  const internal = acvp.sigGen.filter((g) => g.signatureInterface === 'internal');

  it('PCA mlDsa65Sign reproduces the official deterministic signature for every empty-context case; every other case is checked below', () => {
    let viaWrapper = 0;
    for (const g of external.filter((x) => x.deterministic === true)) {
      for (const t of g.tests) {
        if (need(t.context, 'context') !== '') continue;
        const sig = mlDsa65Sign(h(need(t.sk, 'sk')), h(need(t.message, 'message')));
        expect(hex(sig), `tcId ${t.tcId}`).toBe(t.signature);
        viaWrapper += 1;
      }
    }
    expect(viaWrapper).toBeGreaterThanOrEqual(1);
  });

  it('the same ML-DSA reproduces ALL official deterministic external-interface signatures (non-empty contexts)', () => {
    let n = 0;
    for (const g of external.filter((x) => x.deterministic === true)) {
      for (const t of g.tests) {
        const sig = noble.sign(h(need(t.sk, 'sk')), h(need(t.message, 'message')), h(need(t.context, 'context')));
        expect(hex(sig), `tcId ${t.tcId}`).toBe(t.signature);
        n += 1;
      }
    }
    expect(n).toBe(15);
  });

  it('reproduces the randomized (hedged) external-interface signatures given the official rnd', () => {
    for (const g of external.filter((x) => x.deterministic === false)) {
      for (const t of g.tests) {
        const sig = noble.sign(h(need(t.sk, 'sk')), h(need(t.message, 'message')), h(need(t.context, 'context')), h(need(t.rnd, 'rnd')));
        expect(hex(sig), `tcId ${t.tcId}`).toBe(t.signature);
      }
    }
  });

  it('reproduces the internal-interface signatures (message and external-mu variants, deterministic and hedged)', () => {
    let n = 0;
    for (const g of internal) {
      for (const t of g.tests) {
        const input = g.externalMu === true ? need(t.mu, 'mu') : need(t.message, 'message');
        const rnd = g.deterministic === false ? h(need(t.rnd, 'rnd')) : undefined;
        const sig = noble.internal.sign(h(need(t.sk, 'sk')), h(input), rnd, g.externalMu === true);
        expect(hex(sig), `group ${g.tgId} tcId ${t.tcId}`).toBe(t.signature);
        n += 1;
      }
    }
    expect(n).toBe(60);
  });

  it('PCA mlDsa65Verify accepts every official signature that uses an empty context', () => {
    let n = 0;
    for (const g of external) {
      for (const t of g.tests) {
        if (need(t.context, 'context') !== '') continue;
        expect(mlDsa65Verify(h(t.pk), h(need(t.message, 'message')), h(need(t.signature, 'signature')))).toBe(true);
        n += 1;
      }
    }
    expect(n).toBeGreaterThanOrEqual(2);
  });
});

describe('ACVP ML-DSA-65 sigVer (positive and negative, with the official failure reason)', () => {
  it('every official case gets the official verdict (external interface, including non-empty contexts)', () => {
    const reasons = new Map<string, number>();
    for (const g of acvp.sigVer.filter((x) => x.signatureInterface === 'external')) {
      for (const t of g.tests) {
        const ok = noble.verify(h(t.pk), h(need(t.message, 'message')), h(need(t.signature, 'signature')), h(need(t.context, 'context')));
        expect(ok, `tcId ${t.tcId} (${t.reason})`).toBe(t.testPassed);
        reasons.set(need(t.reason, 'reason'), (reasons.get(need(t.reason, 'reason')) ?? 0) + 1);
      }
    }
    // The four official negative classes are all exercised.
    for (const r of ['modified message', 'modified signature - z', 'modified signature - hint', 'modified signature - commitment']) {
      expect(reasons.get(r) ?? 0, r).toBeGreaterThan(0);
    }
  });

  it('every official internal-interface case gets the official verdict', () => {
    for (const g of acvp.sigVer.filter((x) => x.signatureInterface === 'internal')) {
      for (const t of g.tests) {
        const input = g.externalMu === true ? need(t.mu, 'mu') : need(t.message, 'message');
        expect(noble.internal.verify(h(t.pk), h(input), h(need(t.signature, 'signature')), g.externalMu === true), `group ${g.tgId} tcId ${t.tcId} (${t.reason})`).toBe(t.testPassed);
      }
    }
  });

  it('PCA mlDsa65Verify gives the official verdict for every empty-context external case (valid and each negative class)', () => {
    let n = 0;
    for (const g of acvp.sigVer.filter((x) => x.signatureInterface === 'external')) {
      for (const t of g.tests) {
        if (need(t.context, 'context') !== '') continue;
        expect(mlDsa65Verify(h(t.pk), h(need(t.message, 'message')), h(need(t.signature, 'signature'))), `tcId ${t.tcId} (${t.reason})`).toBe(t.testPassed);
        n += 1;
      }
    }
    expect(n).toBeGreaterThanOrEqual(1);
  });

  it('a non-empty-context signature is rejected by PCA (which only speaks the empty context)', () => {
    const g = acvp.sigVer.find((x) => x.signatureInterface === 'external');
    const t = need(g, 'external sigVer group').tests.find((x) => x.testPassed === true && need(x.context, 'context') !== '');
    const tc = need(t, 'a valid non-empty-context case');
    expect(mlDsa65Verify(h(tc.pk), h(need(tc.message, 'message')), h(need(tc.signature, 'signature')))).toBe(false);
  });
});

describe('PCA mlDsa65Verify fail-closed behavior on malformed input', () => {
  const kp = mlDsa65Keygen(new Uint8Array(32).fill(7));
  const msg = new TextEncoder().encode('step-up');
  const sig = mlDsa65Sign(kp.secretKey, msg);
  it('accepts the genuine signature with the expected sizes', () => {
    expect(kp.publicKey.length).toBe(ML_DSA_65_PUBLIC_KEY_BYTES);
    expect(sig.length).toBe(ML_DSA_65_SIGNATURE_BYTES);
    expect(mlDsa65Verify(kp.publicKey, msg, sig)).toBe(true);
  });
  it('rejects truncated / extended keys and signatures (wrong length, never throws)', () => {
    expect(mlDsa65Verify(kp.publicKey.slice(1), msg, sig)).toBe(false);
    expect(mlDsa65Verify(kp.publicKey, msg, sig.slice(1))).toBe(false);
    expect(mlDsa65Verify(kp.publicKey, msg, new Uint8Array([...sig, 0]))).toBe(false);
    expect(mlDsa65Verify(new Uint8Array(0), msg, new Uint8Array(0))).toBe(false);
  });
  it('rejects a flip in each region of the signature: commitment hash, z, hint', () => {
    const regions: [string, number][] = [['commitment hash', 0], ['z', 48 + 10], ['hint', ML_DSA_65_SIGNATURE_BYTES - 1]];
    for (const [name, i] of regions) {
      const bad = Uint8Array.from(sig);
      bad[i] = (bad[i] ?? 0) ^ 0x01;
      expect(mlDsa65Verify(kp.publicKey, msg, bad), name).toBe(false);
    }
  });
  it('rejects a different key and a different message', () => {
    const other = mlDsa65Keygen(new Uint8Array(32).fill(8));
    expect(mlDsa65Verify(other.publicKey, msg, sig)).toBe(false);
    expect(mlDsa65Verify(kp.publicKey, new TextEncoder().encode('step-up!'), sig)).toBe(false);
  });
});

interface Cross {
  provenance: { kind: string; independent_implementations: Record<string, string> };
  noble_signed: { seed: string; pk: string; msg: string; sig: string; dilithium_py_verifies: boolean; liboqs_verifies: boolean; tampered_rejected: boolean }[];
  dilithium_py: { seed: string; pk: string; sk: string; msg: string; sig_deterministic: string }[];
  liboqs: { pk: string; msg: string; sig: string }[];
}
const cross = JSON.parse(readFileSync(join(dir, 'crosscheck-ml-dsa-65.json'), 'utf8')) as Cross;

describe('cross-implementation: PCA ML-DSA vs dilithium-py and liboqs (not official vectors)', () => {
  it('records the independent library versions', () => {
    expect(cross.provenance.kind).toMatch(/NOT official/);
    expect(Object.keys(cross.provenance.independent_implementations).sort()).toEqual(['dilithium-py', 'liboqs', 'liboqs-python']);
  });
  it('PCA -> independent: both libraries verified PCA signatures (and rejected tampering) at generation time, and PCA reproduces them', () => {
    for (const c of cross.noble_signed) {
      expect(c.dilithium_py_verifies && c.liboqs_verifies && c.tampered_rejected).toBe(true);
      const kp = mlDsa65Keygen(h(c.seed));
      expect(hex(kp.publicKey)).toBe(c.pk);
      expect(hex(mlDsa65Sign(kp.secretKey, h(c.msg)))).toBe(c.sig);
    }
  });
  it('independent -> PCA: dilithium-py keys derive identically and its deterministic signatures are byte-identical and verify', () => {
    for (const c of cross.dilithium_py) {
      const kp = mlDsa65Keygen(h(c.seed));
      expect(hex(kp.publicKey)).toBe(c.pk);
      expect(hex(kp.secretKey)).toBe(c.sk);
      expect(hex(mlDsa65Sign(kp.secretKey, h(c.msg)))).toBe(c.sig_deterministic);
      expect(mlDsa65Verify(h(c.pk), h(c.msg), h(c.sig_deterministic))).toBe(true);
    }
  });
  it('independent -> PCA: liboqs (hedged) signatures under fresh liboqs keys verify in PCA; tampering does not', () => {
    for (const c of cross.liboqs) {
      expect(mlDsa65Verify(h(c.pk), h(c.msg), h(c.sig))).toBe(true);
      expect(mlDsa65Verify(h(c.pk), new Uint8Array([...h(c.msg), 1]), h(c.sig))).toBe(false);
      const bad = h(c.sig);
      bad[bad.length - 1] = (bad[bad.length - 1] ?? 0) ^ 1;
      expect(mlDsa65Verify(h(c.pk), h(c.msg), bad)).toBe(false);
    }
  });
});
