/**
 * A small, self-contained prime-order elliptic-curve group, used by the base oblivious transfer in
 * `ot.ts`. The no-dealer offline phase (MASCOT-style triple generation) rests on real OT, and real OT
 * rests on a real group with a hard discrete log — this module provides that group with nothing but
 * BigInt arithmetic, so the whole stack stays dependency-free and testable in-process.
 *
 * Curve: **Ed25519** (twisted Edwards `−x² + y² = 1 + d·x²·y²` over `F_q`, `q = 2^255 − 19`). We work
 * exclusively in the prime-order subgroup of order `L = 2^252 + 27742317777372353535851937790883648493`
 * generated by the standard base point `B`, keeping every scalar in `[0, L)`; all group elements we
 * ever form are scalar multiples of subgroup points, so they stay in the subgroup. Points are held in
 * **extended coordinates** `(X, Y, Z, T)` with `x = X/Z`, `y = Y/Z`, `T = XY/Z`, and combined with the
 * unified ("hwcd-3") addition law, which is *complete* on the subgroup — there are no special cases to
 * branch on, which is exactly what keeps the implementation free of the subtle point-at-infinity bugs
 * that plague short-Weierstrass code.
 *
 * SECURITY NOTES (prototype honesty, mirrored in docs §7.1):
 *  - **Point validation IS implemented** (`isOnCurve` / `hasPrimeOrder` / `assertInSubgroup`): every
 *    point a party RECEIVES across the OT trust boundary is validated to be on the curve and in the
 *    prime-order subgroup (cofactor check `[L]·P = O`), and non-identity, so a malicious party cannot
 *    inject an off-curve / small-order / mixed-order point to mount a small-subgroup attack. A
 *    `schnorrProve`/`schnorrVerify` NIZK of knowledge of the sender's discrete log `y` (`S = y·B`)
 *    binds `S` to a known exponent, which — with validation — is what makes the base OT malicious-secure.
 *  - **Constant-time is NOT achieved and cannot be, in pure JS.** BigInt modular arithmetic branches on
 *    operand size and is not constant-time; this is a genuine language/runtime boundary (see docs §7.1),
 *    not a shortcut — full constant-time needs a native/WASM constant-time field, exactly as the TEE
 *    seam needs real hardware. We add what is cheap and honest (constant-time byte comparison for
 *    commitments lives in `ot.ts`), and do not pretend the field layer is constant-time.
 *  - Discrete log in the order-`L` subgroup is the hardness the OT's receiver-choice privacy relies on.
 */

import { createHash } from 'node:crypto';

/** Field prime q = 2^255 − 19. */
export const Q = 2n ** 255n - 19n;

/** Prime order of the base-point subgroup. Scalars live in [0, L). */
export const L = 2n ** 252n + 27742317777372353535851937790883648493n;

// d = −121665 / 121666 (mod q).
const D = modFq(-121665n * invFq(121666n));

/** A curve point in extended twisted-Edwards coordinates (X:Y:Z:T), x=X/Z, y=Y/Z, T=XY/Z. */
export interface Point {
  X: bigint;
  Y: bigint;
  Z: bigint;
  T: bigint;
}

/** The identity (neutral) element, affine (0, 1). */
export const IDENTITY: Point = { X: 0n, Y: 1n, Z: 1n, T: 0n };

/** The standard Ed25519 base point B (a generator of the order-L subgroup). */
export const BASE: Point = fromAffine(
  15112221349535400772501151409588531511454012693041857206046113283949847762202n,
  46316835694926478169428394003475163141307993866256225615783033603165251855960n,
);

/** Canonical representative in [0, q). */
export function modFq(x: bigint): bigint {
  const r = x % Q;
  return r >= 0n ? r : r + Q;
}

/** Modular inverse in F_q via Fermat (q prime): a^(q−2). */
function invFq(a: bigint): bigint {
  return powFq(modFq(a), Q - 2n);
}

function powFq(base: bigint, exp: bigint): bigint {
  let b = modFq(base);
  let e = exp;
  let acc = 1n;
  while (e > 0n) {
    if (e & 1n) acc = (acc * b) % Q;
    b = (b * b) % Q;
    e >>= 1n;
  }
  return acc;
}

function fromAffine(x: bigint, y: bigint): Point {
  const X = modFq(x);
  const Y = modFq(y);
  return { X, Y, Z: 1n, T: modFq(X * Y) };
}

/**
 * Unified complete addition (twisted Edwards a=−1, "add-2008-hwcd-3"). Works for P=Q too (so doubling
 * is just `add(P, P)`), and is complete on the prime-order subgroup — no exceptional cases.
 */
export function add(p1: Point, p2: Point): Point {
  const A = (modFq(p1.Y - p1.X) * modFq(p2.Y - p2.X)) % Q;
  const B = (modFq(p1.Y + p1.X) * modFq(p2.Y + p2.X)) % Q;
  const C = (((p1.T * 2n) % Q) * D % Q) * p2.T % Q;
  const Dd = (((p1.Z * 2n) % Q) * p2.Z) % Q;
  const E = modFq(B - A);
  const F = modFq(Dd - C);
  const G = modFq(Dd + C);
  const H = modFq(B + A);
  return {
    X: (E * F) % Q,
    Y: (G * H) % Q,
    T: (E * H) % Q,
    Z: (F * G) % Q,
  };
}

/**
 * Dedicated doubling (twisted Edwards a=−1, "dbl-2008-hwcd") — cheaper than the unified add, used to
 * speed up the scalar ladder. Complete on the subgroup.
 */
export function dbl(p: Point): Point {
  const A = (p.X * p.X) % Q;
  const B = (p.Y * p.Y) % Q;
  const C = (2n * ((p.Z * p.Z) % Q)) % Q;
  const Dd = modFq(-A); // a·A with a = −1
  const s = modFq(p.X + p.Y);
  const E = modFq((s * s) % Q - A - B);
  const G = modFq(Dd + B);
  const F = modFq(G - C);
  const H = modFq(Dd - B);
  return {
    X: (E * F) % Q,
    Y: (G * H) % Q,
    T: (E * H) % Q,
    Z: (F * G) % Q,
  };
}

/** Scalar multiplication [k]P (double-and-add). k is reduced mod L; k=0 ⇒ identity. */
export function mul(k: bigint, p: Point): Point {
  let e = k % L;
  if (e < 0n) e += L;
  let acc = IDENTITY;
  let base = p;
  while (e > 0n) {
    if (e & 1n) acc = add(acc, base);
    base = dbl(base);
    e >>= 1n;
  }
  return acc;
}

/** [k]·BASE. */
export function mulBase(k: bigint): Point {
  return mul(k, BASE);
}

/** P − Q. */
export function sub(p1: Point, p2: Point): Point {
  return add(p1, neg(p2));
}

/** −P = (−X : Y : Z : −T). */
export function neg(p: Point): Point {
  return { X: modFq(-p.X), Y: p.Y, Z: p.Z, T: modFq(-p.T) };
}

/** Affine (x, y) of a point (one inversion). Identity ⇒ (0, 1). */
export function toAffine(p: Point): { x: bigint; y: bigint } {
  const zinv = invFq(p.Z);
  return { x: modFq(p.X * zinv), y: modFq(p.Y * zinv) };
}

/** Whether two points are equal as group elements (compare in affine). */
export function equal(p1: Point, p2: Point): boolean {
  // X1*Z2 == X2*Z1 and Y1*Z2 == Y2*Z1 (projective equality, no inversion).
  return (
    modFq(p1.X * p2.Z) === modFq(p2.X * p1.Z) && modFq(p1.Y * p2.Z) === modFq(p2.Y * p1.Z)
  );
}

/** 32-byte little-endian encoding of a field element (for hashing points deterministically). */
function feBytes(a: bigint): Uint8Array {
  const out = new Uint8Array(32);
  let v = modFq(a);
  for (let i = 0; i < 32; i++) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

/** Canonical 64-byte encoding of a point (affine x‖y), the input to the OT key-derivation hash. */
export function encodePoint(p: Point): Uint8Array {
  const { x, y } = toAffine(p);
  const out = new Uint8Array(64);
  out.set(feBytes(x), 0);
  out.set(feBytes(y), 32);
  return out;
}

// ==================================================================================================
// POINT VALIDATION (malicious-security hardening, docs §7.1 item b).
//
// A party must never trust a group element received from a (possibly malicious) peer. Three checks
// together reject every point that could enable a small-subgroup / invalid-curve attack:
//   (1) on-curve:   the extended coordinates satisfy the twisted-Edwards equation (and the T-invariant),
//   (2) subgroup:   [L]·P = O, the cofactor check — rejects small-order (order | 8) AND mixed-order
//                   points, so only genuine order-L (prime-order subgroup) points survive,
//   (3) non-identity where the protocol forbids it (S = y·B with y = 0, or a degenerate R).
// These are wired into every OT point decode in `ot.ts`.
// ==================================================================================================

/** Raised when a received point fails on-curve / subgroup / identity validation. */
export class PointValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PointValidationError';
  }
}

/**
 * Scalar multiplication `[k]·P` WITHOUT the mod-L reduction that `mul` applies. `mul` reduces `k mod L`
 * (correct for subgroup scalars, but it would turn `[L]·P` into `[0]·P = O` for every P and so cannot
 * test subgroup membership). This raw ladder is used only by `hasPrimeOrder`.
 */
function scalarMulRaw(k: bigint, p: Point): Point {
  let e = k < 0n ? -k : k;
  let acc = IDENTITY;
  let base = p;
  while (e > 0n) {
    if (e & 1n) acc = add(acc, base);
    base = dbl(base);
    e >>= 1n;
  }
  return acc;
}

/**
 * Whether `p`'s extended coordinates lie on the Ed25519 curve. Checks projectively (no inversion):
 *   - `Z ≠ 0` (a valid projective point),
 *   - the T-invariant `T·Z ≡ X·Y`,
 *   - the twisted-Edwards equation (`a = −1`) cleared of denominators: `(Y² − X²)·Z² ≡ Z⁴ + d·X²·Y²`.
 * An off-curve / malformed point fails here before any scalar work.
 */
export function isOnCurve(p: Point): boolean {
  if (modFq(p.Z) === 0n) return false;
  if (modFq(p.T * p.Z) !== modFq(p.X * p.Y)) return false;
  const X2 = modFq(p.X * p.X);
  const Y2 = modFq(p.Y * p.Y);
  const Z2 = modFq(p.Z * p.Z);
  const lhs = modFq((Y2 - X2) * Z2);
  const Z4 = modFq(Z2 * Z2);
  const dxy = modFq(modFq(D * X2) * Y2);
  const rhs = modFq(Z4 + dxy);
  return lhs === rhs;
}

/** Whether `p` is the identity (neutral) element (affine `(0, 1)`). */
export function isIdentity(p: Point): boolean {
  return equal(p, IDENTITY);
}

/**
 * The cofactor check: whether `[L]·P = O`, i.e. `p` lies in the prime-order-`L` subgroup. For an
 * on-curve point this is true iff `p` has order dividing `L`; since `L` is prime this means order `1`
 * (identity) or order `L`. So on-curve ∧ `hasPrimeOrder` ∧ ¬identity ⟺ a genuine prime-order point.
 * Rejects every small-order point (order | 8) and every mixed-order point (order `h·L`, `h | 8`, `h>1`).
 */
export function hasPrimeOrder(p: Point): boolean {
  return equal(scalarMulRaw(L, p), IDENTITY);
}

/** Whether `p` is a valid non-identity point of the prime-order subgroup (the OT point contract). */
export function isInSubgroup(p: Point): boolean {
  return isOnCurve(p) && !isIdentity(p) && hasPrimeOrder(p);
}

/** Assert `p` is a valid non-identity prime-order-subgroup point, else throw `PointValidationError`. */
export function assertInSubgroup(p: Point, label = 'point'): void {
  if (!isOnCurve(p)) throw new PointValidationError(`${label}: not on curve`);
  if (isIdentity(p)) throw new PointValidationError(`${label}: identity element (forbidden here)`);
  if (!hasPrimeOrder(p)) {
    throw new PointValidationError(`${label}: not in the prime-order subgroup (small-order/cofactor)`);
  }
}

// ==================================================================================================
// SCHNORR NIZK of knowledge of a discrete log (Fiat–Shamir), docs §7.1 item a.
//
// The base-OT sender publishes `S = y·B` and proves it KNOWS `y`. With point validation this is what
// upgrades Chou–Orlandi base OT to malicious security against a cheating SENDER: a sender that uses an
// `S` it cannot open (e.g. a point chosen to leak the receiver's choice, or a point copied/mauled from
// elsewhere) fails the proof, and the receiver ABORTS before it ever forms `R = x·B + c·S`.
// ==================================================================================================

/** A Fiat–Shamir Schnorr proof of knowledge of `y` s.t. `S = y·B`: commitment `U = r·B` and `z = r + e·y`. */
export interface SchnorrProof {
  U: Point;
  z: bigint;
}

const TAG_SCHNORR = new TextEncoder().encode('atlas-pca-mpc/schnorr-dlog');

/** Fiat–Shamir challenge `e = H(tag ‖ B ‖ S ‖ U) mod L` (64 hash bytes ⇒ negligible modular bias). */
function schnorrChallenge(S: Point, U: Point): bigint {
  const d = createHash('sha512')
    .update(TAG_SCHNORR)
    .update(encodePoint(BASE))
    .update(encodePoint(S))
    .update(encodePoint(U))
    .digest();
  let acc = 0n;
  for (const b of d) acc = (acc << 8n) | BigInt(b);
  return acc % L;
}

/** Prove knowledge of `y` with `S = y·B`. `rnd` draws the (secret) nonce `r ∈ [1, L)`. */
export function schnorrProve(y: bigint, S: Point, rnd: () => bigint): SchnorrProof {
  // The nonce must be a non-zero subgroup scalar; `rnd` already draws from [1, L), the guard is belt-and-braces.
  let r = ((rnd() % L) + L) % L;
  if (r === 0n) r = 1n;
  const U = mulBase(r);
  const e = schnorrChallenge(S, U);
  let z = (r + e * (((y % L) + L) % L)) % L;
  if (z < 0n) z += L;
  return { U, z };
}

/**
 * Verify a Schnorr proof for `S`: `z` is in range, `U` is a valid subgroup point, and `z·B = U + e·S`
 * for the recomputed challenge `e`. Returns false on any failure (the OT layer turns that into an abort).
 */
export function schnorrVerify(S: Point, proof: SchnorrProof): boolean {
  if (proof.z < 0n || proof.z >= L) return false;
  if (!isInSubgroup(proof.U)) return false;
  const e = schnorrChallenge(S, proof.U);
  return equal(mulBase(proof.z), add(proof.U, mul(e, S)));
}
