/**
 * A small, self-contained prime-order elliptic-curve group, used by the base oblivious transfer in
 * `ot.ts`. The no-dealer offline phase (MASCOT-style triple generation) rests on real OT, and real OT
 * rests on a real group with a hard discrete log — this module provides that group with nothing but
 * BigInt arithmetic, so the whole stack stays dependency-free and testable in-process.
 *
 * Curve: **Ed25519** (twisted Edwards `−x² + y² = 1 + d·x²·y²` over `F_q`, `q = 2^255 − 19`). We work
 * exclusively in the prime-order subgroup of order `L = 2^252 + 27742317777372353535851937790883648493`
 * generated by the standard base point `B`, keeping every scalar in `[0, L)`; all group elements we
 * ever form are scalar multiples of subgroup points, so they stay in the subgroup. Points are held in
 * **extended coordinates** `(X, Y, Z, T)` with `x = X/Z`, `y = Y/Z`, `T = XY/Z`, and combined with the
 * unified ("hwcd-3") addition law, which is *complete* on the subgroup — there are no special cases to
 * branch on, which is exactly what keeps the implementation free of the subtle point-at-infinity bugs
 * that plague short-Weierstrass code.
 *
 * SECURITY NOTES (prototype honesty, mirrored in docs §7.1):
 *  - **Point validation IS implemented** (`isOnCurve` / `hasPrimeOrder` / `assertInSubgroup`): every
 *    point a party RECEIVES across the OT trust boundary is validated to be on the curve and in the
 *    prime-order subgroup (cofactor check `[L]·P = O`), and non-identity, so a malicious party cannot
 *    inject an off-curve / small-order / mixed-order point to mount a small-subgroup attack. A
 *    `schnorrProve`/`schnorrVerify` NIZK of knowledge of the sender's discrete log `y` (`S = y·B`)
 *    binds `S` to a known exponent, which — with validation — is what makes the base OT malicious-secure.
 *  - **Constant-time: the secret-scalar multiplications now run in a constant-time WASM core by
 *    DEFAULT.** BigInt modular arithmetic branches on operand size and is not constant-time; rather than
 *    pretend otherwise, the security-critical ops (every secret-scalar multiply/point-combine: `mulBase`,
 *    `mul`, `add`, `sub`, `neg`, and the `[L]·P` cofactor ladder) are routed through `@atlasauth/pca-mpc-wasm`
 *    (a `curve25519-dalek` core compiled to WebAssembly) whenever it loads, which is the default. The
 *    pure-BigInt path below is retained verbatim as a graceful fallback for when the WASM core is
 *    unavailable, and is proven byte-for-byte equivalent to it (see the backend section and
 *    `ec-wasm.test.ts`). The remaining BigInt marshalling (point compress/decompress) operates on
 *    public point values, never the secret scalar, and is not claimed constant-time (docs §7.1).
 *  - Discrete log in the order-`L` subgroup is the hardness the OT's receiver-choice privacy relies on.
 */

import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { join } from 'node:path';

/** Field prime q = 2^255 − 19. */
export const Q = 2n ** 255n - 19n;

/** Prime order of the base-point subgroup. Scalars live in [0, L). */
export const L = 2n ** 252n + 27742317777372353535851937790883648493n;

// d = −121665 / 121666 (mod q).
const D = modFq(-121665n * invFq(121666n));

// √(−1) mod q = 2^((q−1)/4) (used by the point decompression that round-trips the WASM core's
// canonical 32-byte compressed encoding back into an extended-coordinate `Point`).
const SQRT_M1 = powFq(2n, (Q - 1n) / 4n);

/** A curve point in extended twisted-Edwards coordinates (X:Y:Z:T), x=X/Z, y=Y/Z, T=XY/Z. */
export interface Point {
  X: bigint;
  Y: bigint;
  Z: bigint;
  T: bigint;
}

/** The identity (neutral) element, affine (0, 1). */
export const IDENTITY: Point = { X: 0n, Y: 1n, Z: 1n, T: 0n };

/** The standard Ed25519 base point B (a generator of the order-L subgroup). */
export const BASE: Point = fromAffine(
  15112221349535400772501151409588531511454012693041857206046113283949847762202n,
  46316835694926478169428394003475163141307993866256225615783033603165251855960n,
);

/** Canonical representative in [0, q). */
export function modFq(x: bigint): bigint {
  const r = x % Q;
  return r >= 0n ? r : r + Q;
}

/** Modular inverse in F_q via Fermat (q prime): a^(q−2). */
function invFq(a: bigint): bigint {
  return powFq(modFq(a), Q - 2n);
}

function powFq(base: bigint, exp: bigint): bigint {
  let b = modFq(base);
  let e = exp;
  let acc = 1n;
  while (e > 0n) {
    if (e & 1n) acc = (acc * b) % Q;
    b = (b * b) % Q;
    e >>= 1n;
  }
  return acc;
}

function fromAffine(x: bigint, y: bigint): Point {
  const X = modFq(x);
  const Y = modFq(y);
  return { X, Y, Z: 1n, T: modFq(X * Y) };
}

/**
 * Unified complete addition (twisted Edwards a=−1, "add-2008-hwcd-3"). Works for P=Q too (so doubling
 * is just `add(P, P)`), and is complete on the prime-order subgroup — no exceptional cases.
 */
function addPure(p1: Point, p2: Point): Point {
  const A = (modFq(p1.Y - p1.X) * modFq(p2.Y - p2.X)) % Q;
  const B = (modFq(p1.Y + p1.X) * modFq(p2.Y + p2.X)) % Q;
  const C = (((p1.T * 2n) % Q) * D % Q) * p2.T % Q;
  const Dd = (((p1.Z * 2n) % Q) * p2.Z) % Q;
  const E = modFq(B - A);
  const F = modFq(Dd - C);
  const G = modFq(Dd + C);
  const H = modFq(B + A);
  return {
    X: (E * F) % Q,
    Y: (G * H) % Q,
    T: (E * H) % Q,
    Z: (F * G) % Q,
  };
}

/**
 * Dedicated doubling (twisted Edwards a=−1, "dbl-2008-hwcd") — cheaper than the unified add, used to
 * speed up the scalar ladder. Complete on the subgroup.
 */
export function dbl(p: Point): Point {
  const A = (p.X * p.X) % Q;
  const B = (p.Y * p.Y) % Q;
  const C = (2n * ((p.Z * p.Z) % Q)) % Q;
  const Dd = modFq(-A); // a·A with a = −1
  const s = modFq(p.X + p.Y);
  const E = modFq((s * s) % Q - A - B);
  const G = modFq(Dd + B);
  const F = modFq(G - C);
  const H = modFq(Dd - B);
  return {
    X: (E * F) % Q,
    Y: (G * H) % Q,
    T: (E * H) % Q,
    Z: (F * G) % Q,
  };
}

/** Scalar multiplication [k]P (double-and-add), pure-BigInt. k is reduced mod L; k=0 ⇒ identity. */
function mulPure(k: bigint, p: Point): Point {
  let e = k % L;
  if (e < 0n) e += L;
  let acc = IDENTITY;
  let base = p;
  while (e > 0n) {
    if (e & 1n) acc = addPure(acc, base);
    base = dbl(base);
    e >>= 1n;
  }
  return acc;
}

/** [k]·BASE, pure-BigInt. */
function mulBasePure(k: bigint): Point {
  return mulPure(k, BASE);
}

/** P − Q, pure-BigInt. */
function subPure(p1: Point, p2: Point): Point {
  return addPure(p1, negPure(p2));
}

/** −P = (−X : Y : Z : −T), pure-BigInt. */
function negPure(p: Point): Point {
  return { X: modFq(-p.X), Y: p.Y, Z: p.Z, T: modFq(-p.T) };
}

// ==================================================================================================
// CONSTANT-TIME CURVE BACKEND (docs §7.1 item: the JS/runtime constant-time boundary).
//
// The pure-BigInt group law above is correct and malicious-hardened, but BigInt modular arithmetic is
// NOT — and in pure JS cannot be — constant-time: it branches on operand size, so a secret scalar `k`
// multiplied into the curve (`S = y·B`, `T = y·S`, `R = x·B (+S)`, `y·R`, `x·S`) leaks through timing.
// `@atlasauth/pca-mpc-wasm` is a small `curve25519-dalek` core compiled to WebAssembly whose field and
// scalar multiplication ARE audited and constant-time. When it loads (the default), every SECRET-scalar
// multiplication and point combination below runs inside it; if it is unavailable the pure-BigInt path
// is used unchanged. The two are proven byte-for-byte equivalent (the wasm package's parity test vs.
// `@noble/curves`, and `ec-wasm.test.ts` here vs. this pure path), so switching backends never changes
// an observable result — only the timing profile of the secret-dependent ops.
//
// Marshalling boundary (honest, docs §7.1): a `Point` is bridged to the core as its canonical 32-byte
// compressed encoding and back. Compression/decompression themselves stay in BigInt and are NOT claimed
// constant-time — but they operate on POINTS (public wire values / the hashed OT pads), never on the
// secret scalar, whose ladder is the timing-critical surface and now runs entirely in the core.
// Compression is faithful ONLY for on-curve points (a compressed encoding stores `y` + a sign bit and
// re-derives `x` on the curve); OFF-curve detection therefore necessarily stays in the pure
// `isOnCurve`, which is why point VALIDATION keeps its BigInt on-curve test and routes only the
// (on-curve) `[L]·P` cofactor ladder through the core.
// ==================================================================================================

/** The subset of the WASM curve core's C-ABI surface consumed here (see `@atlasauth/pca-mpc-wasm`). */
interface WasmCurve {
  mulBase(k: bigint): Uint8Array;
  mul(k: bigint, p: Uint8Array): Uint8Array;
  add(a: Uint8Array, b: Uint8Array): Uint8Array;
  sub(a: Uint8Array, b: Uint8Array): Uint8Array;
  neg(a: Uint8Array): Uint8Array;
  isOnCurve(p: Uint8Array): boolean;
  isIdentity(p: Uint8Array): boolean;
  isInSubgroup(p: Uint8Array): boolean;
}

/** `undefined` = not yet probed; `null` = probed and unavailable (use the pure fallback). */
let wasmBackend: WasmCurve | null | undefined;

/** Narrow an opaque module to the `WasmCurve` surface without using `any` — every op must be present. */
function asWasmCurve(mod: unknown): WasmCurve | null {
  if (typeof mod !== 'object' || mod === null) return null;
  const m = mod as Record<string, unknown>;
  const needed = ['mulBase', 'mul', 'add', 'sub', 'neg', 'isOnCurve', 'isIdentity', 'isInSubgroup'];
  for (const name of needed) {
    if (typeof m[name] !== 'function') return null;
  }
  return mod as WasmCurve;
}

/**
 * Lazily load the constant-time WASM curve core, once. Tries the resolved workspace dependency first,
 * then the sibling package's built `dist` (the stable path whether this module runs from `src` under
 * vitest or from `dist` after a build — `__dirname/../../pca-mpc-wasm/dist` is the same in both). Any
 * failure (package missing, wasm cannot instantiate) is swallowed and pins the pure-BigInt fallback.
 */
function wasmCurve(): WasmCurve | null {
  if (wasmBackend !== undefined) return wasmBackend;
  wasmBackend = null;
  try {
    const require = createRequire(__filename);
    const candidates = [
      '@atlasauth/pca-mpc-wasm',
      join(__dirname, '..', '..', 'pca-mpc-wasm', 'dist', 'index.js'),
    ];
    for (const spec of candidates) {
      try {
        const loaded = asWasmCurve(require(spec));
        if (loaded !== null) {
          wasmBackend = loaded;
          break;
        }
      } catch {
        // try the next candidate
      }
    }
  } catch {
    wasmBackend = null;
  }
  return wasmBackend;
}

/** Whether the constant-time WASM curve backend is active (else the pure-BigInt path is in use). */
export function isWasmCurveActive(): boolean {
  return wasmCurve() !== null;
}

/**
 * Canonical 32-byte compressed Ed25519 encoding of a point (little-endian `y`, sign of `x` in bit 255)
 * — the wire form the WASM core speaks. Faithful for on-curve points; the matching inverse is
 * `decompressPoint`.
 */
export function compressPoint(p: Point): Uint8Array {
  const { x, y } = toAffine(p);
  const out = feBytes(y);
  out[31] = (out[31]! | (Number(x & 1n) << 7)) & 0xff;
  return out;
}

/**
 * Decode a canonical 32-byte compressed encoding back into an extended-coordinate `Point` (RFC 8032
 * §5.1.3 x-recovery). Used to bring a WASM-core result back into the `Point` representation so the rest
 * of `ec.ts`/`ot.ts` (affine encoding, KDF hashing, equality) sees byte-identical values to the pure
 * path. Throws `PointValidationError` on a non-canonical / off-curve encoding.
 */
export function decompressPoint(bytes: Uint8Array): Point {
  if (bytes.length !== 32) throw new PointValidationError('decompressPoint: expected 32 bytes');
  const sign = (bytes[31]! >> 7) & 1;
  let y = 0n;
  for (let i = 0; i < 32; i++) y |= BigInt(bytes[i]!) << BigInt(8 * i);
  y &= (1n << 255n) - 1n; // clear the sign bit
  if (y >= Q) throw new PointValidationError('decompressPoint: non-canonical y (≥ q)');
  const y2 = modFq(y * y);
  const u = modFq(y2 - 1n);
  const v = modFq(D * y2 + 1n);
  const v3 = modFq(modFq(v * v) * v);
  const v7 = modFq(modFq(v3 * v3) * v);
  let x = modFq(modFq(u * v3) * powFq(modFq(u * v7), (Q - 5n) / 8n));
  const vx2 = modFq(v * modFq(x * x));
  if (vx2 === modFq(u)) {
    // x is correct as-is
  } else if (vx2 === modFq(-u)) {
    x = modFq(x * SQRT_M1);
  } else {
    throw new PointValidationError('decompressPoint: not on curve');
  }
  if (x === 0n && sign === 1) throw new PointValidationError('decompressPoint: non-canonical sign');
  if (Number(x & 1n) !== sign) x = modFq(Q - x);
  return fromAffine(x, y);
}

// --- Public group-op dispatchers: constant-time WASM core when loaded, pure BigInt otherwise. ---

/**
 * Unified complete addition P + Q. Routes through the constant-time WASM core when available (inputs
 * are on-curve points everywhere the OT stack calls this), else the pure-BigInt `add-2008-hwcd-3`.
 */
export function add(p1: Point, p2: Point): Point {
  const w = wasmCurve();
  if (w !== null) return decompressPoint(w.add(compressPoint(p1), compressPoint(p2)));
  return addPure(p1, p2);
}

/** Scalar multiplication [k]P (k reduced mod L; k=0 ⇒ identity). WASM core when available. */
export function mul(k: bigint, p: Point): Point {
  const w = wasmCurve();
  if (w !== null) return decompressPoint(w.mul(k, compressPoint(p)));
  return mulPure(k, p);
}

/** [k]·BASE. WASM core when available (the fixed-base secret-scalar multiply). */
export function mulBase(k: bigint): Point {
  const w = wasmCurve();
  if (w !== null) return decompressPoint(w.mulBase(k));
  return mulBasePure(k);
}

/** P − Q. WASM core when available. */
export function sub(p1: Point, p2: Point): Point {
  const w = wasmCurve();
  if (w !== null) return decompressPoint(w.sub(compressPoint(p1), compressPoint(p2)));
  return subPure(p1, p2);
}

/** −P. WASM core when available. */
export function neg(p: Point): Point {
  const w = wasmCurve();
  if (w !== null) return decompressPoint(w.neg(compressPoint(p)));
  return negPure(p);
}

/** Affine (x, y) of a point (one inversion). Identity ⇒ (0, 1). */
export function toAffine(p: Point): { x: bigint; y: bigint } {
  const zinv = invFq(p.Z);
  return { x: modFq(p.X * zinv), y: modFq(p.Y * zinv) };
}

/** Whether two points are equal as group elements (compare in affine). */
export function equal(p1: Point, p2: Point): boolean {
  // X1*Z2 == X2*Z1 and Y1*Z2 == Y2*Z1 (projective equality, no inversion).
  return (
    modFq(p1.X * p2.Z) === modFq(p2.X * p1.Z) && modFq(p1.Y * p2.Z) === modFq(p2.Y * p1.Z)
  );
}

/** 32-byte little-endian encoding of a field element (for hashing points deterministically). */
function feBytes(a: bigint): Uint8Array {
  const out = new Uint8Array(32);
  let v = modFq(a);
  for (let i = 0; i < 32; i++) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

/** Canonical 64-byte encoding of a point (affine x‖y), the input to the OT key-derivation hash. */
export function encodePoint(p: Point): Uint8Array {
  const { x, y } = toAffine(p);
  const out = new Uint8Array(64);
  out.set(feBytes(x), 0);
  out.set(feBytes(y), 32);
  return out;
}

// ==================================================================================================
// POINT VALIDATION (malicious-security hardening, docs §7.1 item b).
//
// A party must never trust a group element received from a (possibly malicious) peer. Three checks
// together reject every point that could enable a small-subgroup / invalid-curve attack:
//   (1) on-curve:   the extended coordinates satisfy the twisted-Edwards equation (and the T-invariant),
//   (2) subgroup:   [L]·P = O, the cofactor check — rejects small-order (order | 8) AND mixed-order
//                   points, so only genuine order-L (prime-order subgroup) points survive,
//   (3) non-identity where the protocol forbids it (S = y·B with y = 0, or a degenerate R).
// These are wired into every OT point decode in `ot.ts`.
// ==================================================================================================

/** Raised when a received point fails on-curve / subgroup / identity validation. */
export class PointValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PointValidationError';
  }
}

/**
 * Scalar multiplication `[k]·P` WITHOUT the mod-L reduction that `mul` applies. `mul` reduces `k mod L`
 * (correct for subgroup scalars, but it would turn `[L]·P` into `[0]·P = O` for every P and so cannot
 * test subgroup membership). This raw ladder is used only by `hasPrimeOrder`.
 */
function scalarMulRaw(k: bigint, p: Point): Point {
  let e = k < 0n ? -k : k;
  let acc = IDENTITY;
  let base = p;
  while (e > 0n) {
    if (e & 1n) acc = addPure(acc, base);
    base = dbl(base);
    e >>= 1n;
  }
  return acc;
}

/**
 * Whether `p`'s extended coordinates lie on the Ed25519 curve. Checks projectively (no inversion):
 *   - `Z ≠ 0` (a valid projective point),
 *   - the T-invariant `T·Z ≡ X·Y`,
 *   - the twisted-Edwards equation (`a = −1`) cleared of denominators: `(Y² − X²)·Z² ≡ Z⁴ + d·X²·Y²`.
 * An off-curve / malformed point fails here before any scalar work.
 */
export function isOnCurve(p: Point): boolean {
  if (modFq(p.Z) === 0n) return false;
  if (modFq(p.T * p.Z) !== modFq(p.X * p.Y)) return false;
  const X2 = modFq(p.X * p.X);
  const Y2 = modFq(p.Y * p.Y);
  const Z2 = modFq(p.Z * p.Z);
  const lhs = modFq((Y2 - X2) * Z2);
  const Z4 = modFq(Z2 * Z2);
  const dxy = modFq(modFq(D * X2) * Y2);
  const rhs = modFq(Z4 + dxy);
  return lhs === rhs;
}

/** Whether `p` is the identity (neutral) element (affine `(0, 1)`). */
export function isIdentity(p: Point): boolean {
  return equal(p, IDENTITY);
}

/**
 * The cofactor check: whether `[L]·P = O`, i.e. `p` lies in the prime-order-`L` subgroup. For an
 * on-curve point this is true iff `p` has order dividing `L`; since `L` is prime this means order `1`
 * (identity) or order `L`. So on-curve ∧ `hasPrimeOrder` ∧ ¬identity ⟺ a genuine prime-order point.
 * Rejects every small-order point (order | 8) and every mixed-order point (order `h·L`, `h | 8`, `h>1`).
 */
function hasPrimeOrderPure(p: Point): boolean {
  return equal(scalarMulRaw(L, p), IDENTITY);
}

/**
 * The cofactor check `[L]·P = O`. When the constant-time WASM core is loaded, the `[L]·P` scalar work
 * runs inside it (the point is compressed to its canonical 32-byte form — faithful for ON-curve points,
 * which is the only case this is reached with in the validation flow — and the core's torsion check is
 * exactly `[L]·P = O`); otherwise it falls back to the pure-BigInt raw ladder. Both agree bit-for-bit
 * (the `[L]·P = O ⟺ torsion-free ∨ identity` equivalence), so the observable result is identical.
 */
export function hasPrimeOrder(p: Point): boolean {
  const w = wasmCurve();
  if (w !== null && isOnCurve(p)) {
    const c = compressPoint(p);
    // torsion-free ⟺ order 1 or L; include the identity explicitly so this matches the pure
    // `[L]·O = O ⇒ true` semantics (the pure ladder returns true for the identity too).
    return w.isInSubgroup(c) || w.isIdentity(c);
  }
  return hasPrimeOrderPure(p);
}

/** Whether `p` is a valid non-identity point of the prime-order subgroup (the OT point contract). */
export function isInSubgroup(p: Point): boolean {
  return isOnCurve(p) && !isIdentity(p) && hasPrimeOrder(p);
}

/** Assert `p` is a valid non-identity prime-order-subgroup point, else throw `PointValidationError`. */
export function assertInSubgroup(p: Point, label = 'point'): void {
  if (!isOnCurve(p)) throw new PointValidationError(`${label}: not on curve`);
  if (isIdentity(p)) throw new PointValidationError(`${label}: identity element (forbidden here)`);
  if (!hasPrimeOrder(p)) {
    throw new PointValidationError(`${label}: not in the prime-order subgroup (small-order/cofactor)`);
  }
}

// ==================================================================================================
// SCHNORR NIZK of knowledge of a discrete log (Fiat–Shamir), docs §7.1 item a.
//
// The base-OT sender publishes `S = y·B` and proves it KNOWS `y`. With point validation this is what
// upgrades Chou–Orlandi base OT to malicious security against a cheating SENDER: a sender that uses an
// `S` it cannot open (e.g. a point chosen to leak the receiver's choice, or a point copied/mauled from
// elsewhere) fails the proof, and the receiver ABORTS before it ever forms `R = x·B + c·S`.
// ==================================================================================================

/** A Fiat–Shamir Schnorr proof of knowledge of `y` s.t. `S = y·B`: commitment `U = r·B` and `z = r + e·y`. */
export interface SchnorrProof {
  U: Point;
  z: bigint;
}

const TAG_SCHNORR = new TextEncoder().encode('atlas-pca-mpc/schnorr-dlog');

/** Fiat–Shamir challenge `e = H(tag ‖ B ‖ S ‖ U) mod L` (64 hash bytes ⇒ negligible modular bias). */
function schnorrChallenge(S: Point, U: Point): bigint {
  const d = createHash('sha512')
    .update(TAG_SCHNORR)
    .update(encodePoint(BASE))
    .update(encodePoint(S))
    .update(encodePoint(U))
    .digest();
  let acc = 0n;
  for (const b of d) acc = (acc << 8n) | BigInt(b);
  return acc % L;
}

/** Prove knowledge of `y` with `S = y·B`. `rnd` draws the (secret) nonce `r ∈ [1, L)`. */
export function schnorrProve(y: bigint, S: Point, rnd: () => bigint): SchnorrProof {
  // The nonce must be a non-zero subgroup scalar; `rnd` already draws from [1, L), the guard is belt-and-braces.
  let r = ((rnd() % L) + L) % L;
  if (r === 0n) r = 1n;
  const U = mulBase(r);
  const e = schnorrChallenge(S, U);
  let z = (r + e * (((y % L) + L) % L)) % L;
  if (z < 0n) z += L;
  return { U, z };
}

/**
 * Verify a Schnorr proof for `S`: `z` is in range, `U` is a valid subgroup point, and `z·B = U + e·S`
 * for the recomputed challenge `e`. Returns false on any failure (the OT layer turns that into an abort).
 */
export function schnorrVerify(S: Point, proof: SchnorrProof): boolean {
  if (proof.z < 0n || proof.z >= L) return false;
  if (!isInSubgroup(proof.U)) return false;
  const e = schnorrChallenge(S, proof.U);
  return equal(mulBase(proof.z), add(proof.U, mul(e, S)));
}
