// Regenerates crosscheck-ml-kem-768.json (NOT official vectors): the wasm K-PKE core vs kyber-py (FIPS 203).
// Requires the built ../dist. Usage: node testdata/crosscheck-ml-kem.mjs <venv-python>
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const w = require(join(here, '..', 'dist', 'index.js'));
const py = process.argv[2];
if (!py) throw new Error('usage: crosscheck-ml-kem.mjs <venv-python>');
const hx = (b) => Buffer.from(b).toString('hex');
const un = (s) => new Uint8Array(Buffer.from(s, 'hex'));
const sh = (label, n) => createHash('shake256', { outputLength: n }).update(label).digest();

const N = 8;
const wasm_keys = [];
for (let i = 0; i < N; i++) {
  const seed = sh(`kem-seed-${i}`, 32), m = sh(`kem-m-${i}`, 32), coins = sh(`kem-coins-${i}`, 32);
  const kp = w.kpkeKeygen(seed);
  const ct = w.kpkeEnc(kp.publicKey, m, coins);
  if (hx(w.kpkeDec(kp.secretKey, ct)) !== hx(m)) throw new Error('wasm self round-trip failed');
  wasm_keys.push({ seed: hx(seed), pk: hx(kp.publicKey), sk: hx(kp.secretKey), m: hx(m), coins: hx(coins), ct_wasm: hx(ct) });
}
const py_keys = Array.from({ length: N }, (_, i) => ({ d: hx(sh(`kem-pyd-${i}`, 32)), m: hx(sh(`kem-pym-${i}`, 32)), coins: hx(sh(`kem-pyc-${i}`, 32)) }));
const ring_inputs = ['', '00', hx(Buffer.from('atlas-ot/branch0')), hx(sh('ring-long', 600)), hx(sh('ring-4096', 4096))];
const uniform = ring_inputs.map((inp, i) => {
  const t = w.hashToRing(un(inp));
  const rho = sh(`uni-rho-${i}`, 32);
  const pk = new Uint8Array([...t, ...rho]);
  const m = sh(`uni-m-${i}`, 32), coins = sh(`uni-c-${i}`, 32);
  return { pk: hx(pk), m: hx(m), coins: hx(coins), ct_wasm: hx(w.kpkeEnc(pk, m, coins)) };
});
const raw = execFileSync(py, ['-I', join(here, 'crosscheck_ml_kem.py')], { input: JSON.stringify({ wasm_keys, py_keys, uniform_keys: uniform, ring_inputs }), maxBuffer: 1 << 28 }).toString().trim().split('\n');
const res = JSON.parse(raw[raw.length - 1]);
for (const [i, r] of res.wasm_keys_checked.entries()) {
  if (r.ct_kyber_py !== wasm_keys[i].ct_wasm || !r.kyber_py_decrypts_wasm_ct || !r.kyber_py_decrypts_own_ct_under_wasm_sk) throw new Error(`kyber-py disagrees on wasm key ${i}`);
}
for (const [i, r] of res.uniform_checked.entries()) if (r.ct !== uniform[i].ct_wasm) throw new Error(`kyber-py disagrees on uniform key ${i}`);
for (const [i, r] of res.hash_to_ring.entries()) if (r.out !== hx(w.hashToRing(un(ring_inputs[i])))) throw new Error(`hashToRing disagrees with independent sampler (${i})`);
for (const r of res.py_keys) {
  const ct = w.kpkeEnc(un(r.ek), un(r.m), un(r.coins));
  if (hx(ct) !== r.ct) throw new Error('wasm enc differs from kyber-py under a kyber-py key');
  if (hx(w.kpkeDec(un(r.dk), un(r.ct))) !== r.m) throw new Error('wasm dec failed on a kyber-py ciphertext');
}
const out = {
  provenance: {
    kind: 'cross-implementation vectors generated by this repo (NOT official NIST vectors; see acvp-ml-kem-768.json for those)',
    independent_implementation: res.versions,
    note: 'K-PKE.Encrypt/Decrypt are deterministic given (key, message, coins) and byte-identical between wasm and kyber-py. K-PKE key GENERATION is not (pqc_kyber derives keys as G(d), FIPS 203 as G(d||k)), so keys are cross-checked by interoperability, not equality.',
    generated: new Date().toISOString().slice(0, 10),
  },
  wasm_keys: wasm_keys.map((c, i) => ({ ...c, ct_kyber_py: res.wasm_keys_checked[i].ct_kyber_py })),
  py_keys: res.py_keys,
  uniform_keys: uniform.map((c, i) => ({ ...c, ct_kyber_py: res.uniform_checked[i].ct })),
  hash_to_ring: res.hash_to_ring,
};
writeFileSync(join(here, 'crosscheck-ml-kem-768.json'), JSON.stringify(out, null, 1) + '\n');
console.log('ok', res.versions);
